-- 1. UNHOOK THE DATABASE GATEKEEPER (Allows profiles without auth accounts for demo)
ALTER TABLE profiles DROP CONSTRAINT IF EXISTS profiles_id_fkey;

-- 2. STAGE THE TABLE (Add missing columns if needed)
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS rating DECIMAL(3,2) DEFAULT 5.00;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS review_count INTEGER DEFAULT 0;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS badges JSONB DEFAULT '[]';
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS is_flagged BOOLEAN DEFAULT false;

-- 3. INJECT REAL PERSONAS
INSERT INTO profiles (id, username, full_name, website, avatar_url, rating, review_count, badges, is_flagged) VALUES 
(gen_random_uuid(), 'gamer_handle', 'Display Name', 'City', 'https://api.dicebear.com/7.x/avataaars/svg?seed=gamer_handle', 2.4, 12, '["super_host"]', true),
(gen_random_uuid(), 'epic42914', 'Ethan Baker', 'Jupiter', 'https://api.dicebear.com/7.x/avataaars/svg?seed=epic42914', 4.84, 18, '["reliable"]', false),
(gen_random_uuid(), 'kylienel99', 'Kylie Nelson', 'Singer Island', 'https://api.dicebear.com/7.x/avataaars/svg?seed=kylienel99', 4.59, 23, '[]', false),
(gen_random_uuid(), 'hackedgeneral81', 'Patrick Sanders', 'Jupiter', 'https://api.dicebear.com/7.x/avataaars/svg?seed=hackedgeneral81', 4.69, 39, '[]', false),
(gen_random_uuid(), 'ivory404176', 'Riley Davis', 'Royal Palm Beach', 'https://api.dicebear.com/7.x/avataaars/svg?seed=ivory404176', 4.76, 20, '["always_early", "pbc_veteran"]', false),
(gen_random_uuid(), 'xxda813xx', 'Damian Gomez', 'Juno Beach', 'https://api.dicebear.com/7.x/avataaars/svg?seed=xxda813xx', 4.97, 51, '[]', false),
(gen_random_uuid(), 'brokengamer157', 'Ricky Gonzalez', 'Delray Beach', 'https://api.dicebear.com/7.x/avataaars/svg?seed=brokengamer157', 4.94, 55, '["community_champion"]', false),
(gen_random_uuid(), 'grind813737', 'Paige Coleman', 'Palm Beach Gardens', 'https://api.dicebear.com/7.x/avataaars/svg?seed=grind813737', 4.62, 10, '["always_early", "reliable"]', false),
(gen_random_uuid(), 'blakecol82', 'Blake Coleman', 'Royal Palm Beach', 'https://api.dicebear.com/7.x/avataaars/svg?seed=blakecol82', 4.78, 34, '["community_champion"]', false),
(gen_random_uuid(), 'ryanmur18', 'Ryan Murphy', 'Lake Park', 'https://api.dicebear.com/7.x/avataaars/svg?seed=ryanmur18', 4.75, 14, '["community_champion", "active"]', false),
(gen_random_uuid(), 'xxmaproxx', 'Matthew Torres', 'Belle Glade', 'https://api.dicebear.com/7.x/avataaars/svg?seed=xxmaproxx', 4.53, 55, '["super_host"]', false),
(gen_random_uuid(), 'elijahbro34', 'Elijah Brooks', 'Riviera Beach', 'https://api.dicebear.com/7.x/avataaars/svg?seed=elijahbro34', 4.66, 45, '["community_champion"]', false),
(gen_random_uuid(), 'chasetho31', 'Chase Thomas', 'North Palm Beach', 'https://api.dicebear.com/7.x/avataaars/svg?seed=chasetho31', 4.75, 45, '["pbc_veteran"]', false),
(gen_random_uuid(), 'xxmamasterxx', 'Madison Okafor', 'Palm Beach', 'https://api.dicebear.com/7.x/avataaars/svg?seed=xxmamasterxx', 4.89, 17, '["pbc_veteran", "community_champion"]', false),
(gen_random_uuid(), 'cobaltstriker430', 'Leo Miller', 'Delray Beach', 'https://api.dicebear.com/7.x/avataaars/svg?seed=cobaltstriker430', 4.53, 50, '["active", "always_early"]', false),
(gen_random_uuid(), 'alexandrasmi74', 'Alexandra Smith', 'Juno Beach', 'https://api.dicebear.com/7.x/avataaars/svg?seed=alexandrasmi74', 4.85, 51, '[]', false),
(gen_random_uuid(), 'ivorymadison27', 'Madison Coleman', 'Delray Beach', 'https://api.dicebear.com/7.x/avataaars/svg?seed=ivorymadison27', 4.94, 43, '["always_early", "active"]', false),
(gen_random_uuid(), 'stormslayer968', 'Jacob Wood', 'Tequesta', 'https://api.dicebear.com/7.x/avataaars/svg?seed=stormslayer968', 4.56, 54, '["always_early", "active"]', false),
(gen_random_uuid(), 'courtneymit62', 'Courtney Mitchell', 'Boynton Beach', 'https://api.dicebear.com/7.x/avataaars/svg?seed=courtneymit62', 4.87, 14, '["pbc_veteran"]', false),
(gen_random_uuid(), 'xxpebossxx', 'Pedro Jenkins', 'Wellington', 'https://api.dicebear.com/7.x/avataaars/svg?seed=xxpebossxx', 4.56, 12, '[]', false),
(gen_random_uuid(), 'xxcabarbarianxx', 'Cameron Clark', 'Manalapan', 'https://api.dicebear.com/7.x/avataaars/svg?seed=xxcabarbarianxx', 4.8, 18, '["community_champion", "pbc_veteran"]', false),
(gen_random_uuid(), 'jademia17', 'Mia Price', 'Palm Beach Gardens', 'https://api.dicebear.com/7.x/avataaars/svg?seed=jademia17', 4.59, 42, '["always_early", "reliable"]', false),
(gen_random_uuid(), 'allisonmur94', 'Allison Murphy', 'Tequesta', 'https://api.dicebear.com/7.x/avataaars/svg?seed=allisonmur94', 4.59, 13, '["pbc_veteran", "active"]', false),
(gen_random_uuid(), 'charlottehal99', 'Charlotte Hall', 'Loxahatchee', 'https://api.dicebear.com/7.x/avataaars/svg?seed=charlottehal99', 4.8, 42, '["reliable", "super_host"]', false),
(gen_random_uuid(), 'xxch420xx', 'Chase Robinson', 'Wellington', 'https://api.dicebear.com/7.x/avataaars/svg?seed=xxch420xx', 4.87, 19, '[]', false),
(gen_random_uuid(), 'omegabrittany35', 'Brittany Perez', 'Wellington', 'https://api.dicebear.com/7.x/avataaars/svg?seed=omegabrittany35', 4.96, 39, '["pbc_veteran", "active"]', false),
(gen_random_uuid(), 'echo561431', 'Thomas Mitchell', 'Greenacres', 'https://api.dicebear.com/7.x/avataaars/svg?seed=echo561431', 4.56, 10, '["super_host"]', false),
(gen_random_uuid(), 'victoriaper69', 'Victoria Perez', 'West Palm Beach', 'https://api.dicebear.com/7.x/avataaars/svg?seed=victoriaper69', 4.75, 19, '["super_host", "active"]', false),
(gen_random_uuid(), 'alexiseva68', 'Alexis Evans', 'Boca Raton', 'https://api.dicebear.com/7.x/avataaars/svg?seed=alexiseva68', 4.72, 58, '[]', false),
(gen_random_uuid(), 'pedrogon35', 'Pedro Gonzalez', 'Boca Raton', 'https://api.dicebear.com/7.x/avataaars/svg?seed=pedrogon35', 4.84, 52, '["community_champion", "always_early"]', false),
(gen_random_uuid(), 'onyxmage952', 'Robert Diaz', 'Delray Beach', 'https://api.dicebear.com/7.x/avataaars/svg?seed=onyxmage952', 4.81, 26, '["pbc_veteran", "super_host"]', false),
(gen_random_uuid(), 'cursedshotgun843', 'Cassidy Morgan', 'Royal Palm Beach', 'https://api.dicebear.com/7.x/avataaars/svg?seed=cursedshotgun843', 4.55, 21, '["always_early", "pbc_veteran"]', false),
(gen_random_uuid(), 'xxmabossxx', 'Matthew Nelson', 'Wellington', 'https://api.dicebear.com/7.x/avataaars/svg?seed=xxmabossxx', 4.9, 13, '["super_host", "active"]', false),
(gen_random_uuid(), 'xxcowitchxx', 'Cole Allen', 'Lake Park', 'https://api.dicebear.com/7.x/avataaars/svg?seed=xxcowitchxx', 4.66, 57, '["reliable", "super_host"]', false),
(gen_random_uuid(), 'xxda42xx', 'Dana Long', 'Loxahatchee', 'https://api.dicebear.com/7.x/avataaars/svg?seed=xxda42xx', 4.72, 14, '["community_champion"]', false),
(gen_random_uuid(), 'infernojordan25', 'Jordan Gomez', 'Loxahatchee', 'https://api.dicebear.com/7.x/avataaars/svg?seed=infernojordan25', 4.75, 14, '[]', false),
(gen_random_uuid(), 'crimsongavin62', 'Gavin Sullivan', 'Belle Glade', 'https://api.dicebear.com/7.x/avataaars/svg?seed=crimsongavin62', 4.58, 56, '[]', false),
(gen_random_uuid(), 'xxcolancexx', 'Cole Zhao', 'Lantana', 'https://api.dicebear.com/7.x/avataaars/svg?seed=xxcolancexx', 4.65, 48, '["always_early", "community_champion"]', false),
(gen_random_uuid(), 'aidenmit46', 'Aiden Mitchell', 'Tequesta', 'https://api.dicebear.com/7.x/avataaars/svg?seed=aidenmit46', 4.52, 41, '["active", "community_champion"]', false),
(gen_random_uuid(), 'ivoryisabella96', 'Isabella Hill', 'Boynton Beach', 'https://api.dicebear.com/7.x/avataaars/svg?seed=ivoryisabella96', 4.8, 17, '[]', false),
(gen_random_uuid(), 'neonwesley12', 'Wesley Butler', 'West Palm Beach', 'https://api.dicebear.com/7.x/avataaars/svg?seed=neonwesley12', 4.63, 14, '["always_early", "active"]', false),
(gen_random_uuid(), 'cursedlord338', 'Dylan Parker', 'Royal Palm Beach', 'https://api.dicebear.com/7.x/avataaars/svg?seed=cursedlord338', 4.73, 10, '[]', false),
(gen_random_uuid(), 'xxnoshotgunxx', 'Nora Coleman', 'Riviera Beach', 'https://api.dicebear.com/7.x/avataaars/svg?seed=xxnoshotgunxx', 4.71, 59, '["community_champion", "reliable"]', false),
(gen_random_uuid(), 'jadeshotgun96', 'Gabrielle Baker', 'Wellington', 'https://api.dicebear.com/7.x/avataaars/svg?seed=jadeshotgun96', 4.99, 31, '["active"]', false),
(gen_random_uuid(), 'luckydaniel1', 'Daniel Howard', 'Lantana', 'https://api.dicebear.com/7.x/avataaars/svg?seed=luckydaniel1', 4.79, 29, '["reliable"]', false),
(gen_random_uuid(), 'alejandrojon62', 'Alejandro Jones', 'Lake Worth Beach', 'https://api.dicebear.com/7.x/avataaars/svg?seed=alejandrojon62', 4.98, 47, '["active", "reliable"]', false),
(gen_random_uuid(), 'grindmaster420', 'Elijah Ruiz', 'Tequesta', 'https://api.dicebear.com/7.x/avataaars/svg?seed=grindmaster420', 4.74, 42, '["active", "pbc_veteran"]', false),
(gen_random_uuid(), 'christinabar21', 'Christina Barnes', 'Boca Raton', 'https://api.dicebear.com/7.x/avataaars/svg?seed=christinabar21', 4.96, 20, '["active"]', false),
(gen_random_uuid(), 'victorcox31', 'Victor Cox', 'Wellington', 'https://api.dicebear.com/7.x/avataaars/svg?seed=victorcox31', 4.75, 16, '["pbc_veteran", "active"]', false),
(gen_random_uuid(), 'betadavid39', 'David Murphy', 'Royal Palm Beach', 'https://api.dicebear.com/7.x/avataaars/svg?seed=betadavid39', 4.94, 35, '["pbc_veteran"]', false),
(gen_random_uuid(), 'xxse561xx', 'Serena Howard', 'West Palm Beach', 'https://api.dicebear.com/7.x/avataaars/svg?seed=xxse561xx', 2.4, 14, '[]', true),
(gen_random_uuid(), 'blessedjasmine22', 'Jasmine Foster', 'Delray Beach', 'https://api.dicebear.com/7.x/avataaars/svg?seed=blessedjasmine22', 4.65, 38, '[]', false),
(gen_random_uuid(), 'xxma305xx', 'Madison Richardson', 'Delray Beach', 'https://api.dicebear.com/7.x/avataaars/svg?seed=xxma305xx', 4.97, 28, '[]', false),
(gen_random_uuid(), 'infernopro909', 'Eva Cooper', 'West Palm Beach', 'https://api.dicebear.com/7.x/avataaars/svg?seed=infernopro909', 4.59, 55, '[]', false),
(gen_random_uuid(), 'matthewbar56', 'Matthew Barnes', 'Royal Palm Beach', 'https://api.dicebear.com/7.x/avataaars/svg?seed=matthewbar56', 4.88, 55, '["active", "reliable"]', false),
(gen_random_uuid(), 'demiand18', 'Demi Anderson', 'Boca Raton', 'https://api.dicebear.com/7.x/avataaars/svg?seed=demiand18', 4.65, 37, '["community_champion", "reliable"]', false),
(gen_random_uuid(), 'jasminecol85', 'Jasmine Coleman', 'West Palm Beach', 'https://api.dicebear.com/7.x/avataaars/svg?seed=jasminecol85', 4.57, 54, '["super_host", "reliable"]', false),
(gen_random_uuid(), 'grindpbc931', 'Brenda Russell', 'Delray Beach', 'https://api.dicebear.com/7.x/avataaars/svg?seed=grindpbc931', 4.52, 47, '[]', false),
(gen_random_uuid(), 'hyperdestiny77', 'Destiny Cox', 'Boca Raton', 'https://api.dicebear.com/7.x/avataaars/svg?seed=hyperdestiny77', 4.6, 22, '["active"]', false),
(gen_random_uuid(), 'fiercealejandro33', 'Alejandro Miller', 'Lantana', 'https://api.dicebear.com/7.x/avataaars/svg?seed=fiercealejandro33', 4.66, 49, '["pbc_veteran", "reliable"]', false),
(gen_random_uuid(), 'fiercegenesis16', 'Genesis Robinson', 'Boca Raton', 'https://api.dicebear.com/7.x/avataaars/svg?seed=fiercegenesis16', 4.99, 35, '["reliable", "super_host"]', false),
(gen_random_uuid(), 'ivory239674', 'Eva Zhao', 'Jupiter', 'https://api.dicebear.com/7.x/avataaars/svg?seed=ivory239674', 4.76, 17, '["super_host"]', false),
(gen_random_uuid(), 'danielcox58', 'Daniel Cox', 'West Palm Beach', 'https://api.dicebear.com/7.x/avataaars/svg?seed=danielcox58', 4.57, 40, '[]', false),
(gen_random_uuid(), 'xxivwitchxx', 'Ivan Davis', 'Boca Raton', 'https://api.dicebear.com/7.x/avataaars/svg?seed=xxivwitchxx', 4.94, 33, '["reliable", "active"]', false),
(gen_random_uuid(), 'xxdabarbarianxx', 'Dawn Perez', 'Lake Park', 'https://api.dicebear.com/7.x/avataaars/svg?seed=xxdabarbarianxx', 4.77, 49, '["pbc_veteran"]', false),
(gen_random_uuid(), 'blazegenesis51', 'Genesis Lopez', 'North Palm Beach', 'https://api.dicebear.com/7.x/avataaars/svg?seed=blazegenesis51', 4.57, 18, '["super_host", "reliable"]', false),
(gen_random_uuid(), 'dionngu65', 'Dion Nguyen', 'Royal Palm Beach', 'https://api.dicebear.com/7.x/avataaars/svg?seed=dionngu65', 4.9, 53, '["always_early", "reliable"]', false),
(gen_random_uuid(), 'cassandraram23', 'Cassandra Ramirez', 'Lake Worth Beach', 'https://api.dicebear.com/7.x/avataaars/svg?seed=cassandraram23', 4.75, 43, '["reliable"]', false),
(gen_random_uuid(), 'crimsonlance647', 'Crystal Taylor', 'Greenacres', 'https://api.dicebear.com/7.x/avataaars/svg?seed=crimsonlance647', 4.5, 21, '["reliable"]', false),
(gen_random_uuid(), 'xxchaxexx', 'Chloe Long', 'Palm Beach Gardens', 'https://api.dicebear.com/7.x/avataaars/svg?seed=xxchaxexx', 4.94, 48, '["pbc_veteran"]', false),
(gen_random_uuid(), 'xxbepaladinxx', 'Ben Taylor', 'Boynton Beach', 'https://api.dicebear.com/7.x/avataaars/svg?seed=xxbepaladinxx', 4.99, 60, '["pbc_veteran"]', false),
(gen_random_uuid(), 'omarcar52', 'Omar Carter', 'Palm Springs', 'https://api.dicebear.com/7.x/avataaars/svg?seed=omarcar52', 4.78, 49, '["always_early"]', false),
(gen_random_uuid(), 'biancalew53', 'Bianca Lewis', 'West Palm Beach', 'https://api.dicebear.com/7.x/avataaars/svg?seed=biancalew53', 4.92, 19, '[]', false),
(gen_random_uuid(), 'epicjacob93', 'Jacob Evans', 'Boynton Beach', 'https://api.dicebear.com/7.x/avataaars/svg?seed=epicjacob93', 4.54, 35, '["always_early", "reliable"]', false),
(gen_random_uuid(), 'xxjodruidxx', 'Jordan Long', 'Juno Beach', 'https://api.dicebear.com/7.x/avataaars/svg?seed=xxjodruidxx', 4.74, 11, '[]', false),
(gen_random_uuid(), 'moddedace837', 'Maria Nelson', 'Pahokee', 'https://api.dicebear.com/7.x/avataaars/svg?seed=moddedace837', 4.8, 26, '["community_champion"]', false),
(gen_random_uuid(), 'moddedelijah61', 'Elijah Reyes', 'Greenacres', 'https://api.dicebear.com/7.x/avataaars/svg?seed=moddedelijah61', 4.79, 27, '["pbc_veteran"]', false),
(gen_random_uuid(), 'xxmoslayerxx', 'Morgan Collins', 'Boca Raton', 'https://api.dicebear.com/7.x/avataaars/svg?seed=xxmoslayerxx', 4.62, 50, '[]', false),
(gen_random_uuid(), 'azurerogue520', 'Jenna Torres', 'Boca Raton', 'https://api.dicebear.com/7.x/avataaars/svg?seed=azurerogue520', 4.56, 41, '["super_host", "reliable"]', false),
(gen_random_uuid(), 'luckydana83', 'Dana Wood', 'Greenacres', 'https://api.dicebear.com/7.x/avataaars/svg?seed=luckydana83', 4.64, 50, '[]', false),
(gen_random_uuid(), 'brendamar46', 'Brenda Martinez', 'North Palm Beach', 'https://api.dicebear.com/7.x/avataaars/svg?seed=brendamar46', 4.57, 20, '[]', false),
(gen_random_uuid(), 'casualowen11', 'Owen Evans', 'Belle Glade', 'https://api.dicebear.com/7.x/avataaars/svg?seed=casualowen11', 4.98, 18, '[]', false),
(gen_random_uuid(), 'cobaltjake56', 'Jake Ward', 'Tequesta', 'https://api.dicebear.com/7.x/avataaars/svg?seed=cobaltjake56', 4.71, 23, '["always_early", "super_host"]', false),
(gen_random_uuid(), 'brooklyncox92', 'Brooklyn Cox', 'Tequesta', 'https://api.dicebear.com/7.x/avataaars/svg?seed=brooklyncox92', 4.53, 48, '[]', false),
(gen_random_uuid(), 'xxlo321xx', 'Logan Coleman', 'West Palm Beach', 'https://api.dicebear.com/7.x/avataaars/svg?seed=xxlo321xx', 4.98, 31, '["always_early", "reliable"]', false),
(gen_random_uuid(), 'clutchdavid9', 'David Nelson', 'Boynton Beach', 'https://api.dicebear.com/7.x/avataaars/svg?seed=clutchdavid9', 4.67, 53, '["super_host"]', false),
(gen_random_uuid(), 'xxdexlxx', 'Devon Campbell', 'Boca Raton', 'https://api.dicebear.com/7.x/avataaars/svg?seed=xxdexlxx', 4.58, 23, '["reliable"]', false),
(gen_random_uuid(), 'xxgadruidxx', 'Gavin Castillo', 'Palm Springs', 'https://api.dicebear.com/7.x/avataaars/svg?seed=xxgadruidxx', 4.99, 30, '[]', false),
(gen_random_uuid(), 'cobaltdiana69', 'Diana Harris', 'Lake Worth Beach', 'https://api.dicebear.com/7.x/avataaars/svg?seed=cobaltdiana69', 4.99, 50, '["super_host"]', false),
(gen_random_uuid(), 'xxju813xx', 'Justin Patel', 'Juno Beach', 'https://api.dicebear.com/7.x/avataaars/svg?seed=xxju813xx', 4.52, 44, '["super_host"]', false),
(gen_random_uuid(), 'ultraalexis17', 'Alexis Garcia', 'Greenacres', 'https://api.dicebear.com/7.x/avataaars/svg?seed=ultraalexis17', 4.53, 24, '["always_early"]', false),
(gen_random_uuid(), 'hackedchase74', 'Chase Jackson', 'Riviera Beach', 'https://api.dicebear.com/7.x/avataaars/svg?seed=hackedchase74', 4.82, 57, '["pbc_veteran"]', false),
(gen_random_uuid(), 'goldenliam77', 'Liam Gomez', 'Singer Island', 'https://api.dicebear.com/7.x/avataaars/svg?seed=goldenliam77', 4.91, 17, '["pbc_veteran"]', false),
(gen_random_uuid(), 'blazesofia50', 'Sofia Bennett', 'Juno Beach', 'https://api.dicebear.com/7.x/avataaars/svg?seed=blazesofia50', 4.88, 29, '[]', false),
(gen_random_uuid(), 'xxowdruidxx', 'Owen Robinson', 'Royal Palm Beach', 'https://api.dicebear.com/7.x/avataaars/svg?seed=xxowdruidxx', 4.51, 17, '["always_early", "reliable"]', false),
(gen_random_uuid(), 'onyxolivia44', 'Olivia Scott', 'Greenacres', 'https://api.dicebear.com/7.x/avataaars/svg?seed=onyxolivia44', 4.68, 56, '[]', false),
(gen_random_uuid(), 'briannasan16', 'Brianna Sanchez', 'Loxahatchee', 'https://api.dicebear.com/7.x/avataaars/svg?seed=briannasan16', 4.55, 13, '[]', false),
(gen_random_uuid(), 'xxje1337xx', 'Jessica Anderson', 'Tequesta', 'https://api.dicebear.com/7.x/avataaars/svg?seed=xxje1337xx', 4.97, 27, '["active"]', false),
(gen_random_uuid(), 'epicnicole99', 'Nicole Edwards', 'Palm Beach', 'https://api.dicebear.com/7.x/avataaars/svg?seed=epicnicole99', 4.56, 16, '["always_early", "pbc_veteran"]', false),
(gen_random_uuid(), 'stormashley74', 'Ashley Johnson', 'Loxahatchee', 'https://api.dicebear.com/7.x/avataaars/svg?seed=stormashley74', 4.53, 40, '["pbc_veteran", "active"]', false);