-- ROLLCALL MASTER RESTORATION: 500 RESIDENTS & TRIBAL GROUPS

-- Ensure Tables Exist
CREATE TABLE IF NOT EXISTS public.profiles (id uuid REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY, username text UNIQUE, full_name text, subscription_tier text DEFAULT 'Free', is_verified_organizer boolean DEFAULT false, created_at timestamp with time zone DEFAULT now());
CREATE TABLE IF NOT EXISTS public.groups (id uuid DEFAULT gen_random_uuid() PRIMARY KEY, name text NOT NULL UNIQUE, category text NOT NULL, city text NOT NULL, description text, capacity integer DEFAULT 50, members integer DEFAULT 1, coords jsonb, image text, created_at timestamp with time zone DEFAULT now());
CREATE TABLE IF NOT EXISTS public.memberships (id uuid DEFAULT gen_random_uuid() PRIMARY KEY, user_id uuid REFERENCES auth.users ON DELETE CASCADE, group_id uuid REFERENCES public.groups(id) ON DELETE CASCADE, role text DEFAULT 'member', UNIQUE(user_id, group_id));

-- Robust User Creation Function

CREATE OR REPLACE FUNCTION restore_rollcall_user(
    u_email text, u_password text, u_name text, u_username text, u_is_admin boolean DEFAULT false
) RETURNS uuid AS $$
DECLARE
    target_id uuid;
BEGIN
    SELECT id INTO target_id FROM auth.users WHERE email = u_email;
    
    IF target_id IS NULL THEN
        target_id := gen_random_uuid();
        INSERT INTO auth.users (instance_id, id, aud, role, email, encrypted_password, email_confirmed_at, raw_app_meta_data, raw_user_meta_data, is_super_admin, created_at, updated_at)
        VALUES ('00000000-0000-0000-0000-000000000000', target_id, 'authenticated', 'authenticated', u_email, crypt(u_password, gen_salt('bf')), now(), '{"provider":"email","providers":["email"]}', jsonb_build_object('full_name', u_name), u_is_admin, now(), now());
    END IF;

    INSERT INTO public.profiles (id, username, full_name, subscription_tier, is_verified_organizer)
    VALUES (target_id, u_username, u_name, CASE WHEN u_is_admin THEN 'Pro' ELSE 'Free' END, u_is_admin)
    ON CONFLICT (id) DO UPDATE SET is_verified_organizer = u_is_admin, subscription_tier = CASE WHEN u_is_admin THEN 'Pro' ELSE 'Free' END;

    RETURN target_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- SEEDING SUPER ADMIN
SELECT restore_rollcall_user('craineri76@gmail.com', 'password123', 'Carlo Raineri', 'Carlo_Admin', true);

-- SEEDING 500 RESIDENTS FROM PRODUCTION CSV
SELECT restore_rollcall_user('ethan.baker229@yahoo.com', 'PeakEB21*', 'Ethan Baker229', 'ethan_baker229');
SELECT restore_rollcall_user('kylie.nelson829@gmail.com', 'WildKN53#', 'Kylie Nelson829', 'kylie_nelson829');
SELECT restore_rollcall_user('patrick.sanders748@icloud.com', 'PeakPS47*', 'Patrick Sanders748', 'patrick_sanders748');
SELECT restore_rollcall_user('riley.davis215@outlook.com', 'PeakRD41@', 'Riley Davis215', 'riley_davis215');
SELECT restore_rollcall_user('damian.gomez218@icloud.com', 'FreeDG28#', 'Damian Gomez218', 'damian_gomez218');
SELECT restore_rollcall_user('ricky.gonzalez506@gmail.com', 'FastRG97$', 'Ricky Gonzalez506', 'ricky_gonzalez506');
SELECT restore_rollcall_user('paige.coleman162@icloud.com', 'NeonPC74@', 'Paige Coleman162', 'paige_coleman162');
SELECT restore_rollcall_user('blake.coleman246@gmail.com', 'CoolBC20$', 'Blake Coleman246', 'blake_coleman246');
SELECT restore_rollcall_user('ryan.murphy124@yahoo.com', 'EpicRM12*', 'Ryan Murphy124', 'ryan_murphy124');
SELECT restore_rollcall_user('matthew.torres553@yahoo.com', 'FreeMT62@', 'Matthew Torres553', 'matthew_torres553');
SELECT restore_rollcall_user('elijah.brooks820@gmail.com', 'BoldEB78$', 'Elijah Brooks820', 'elijah_brooks820');
SELECT restore_rollcall_user('chase.thomas993@gmail.com', 'WildCT72$', 'Chase Thomas993', 'chase_thomas993');
SELECT restore_rollcall_user('madison.okafor434@hotmail.com', 'BoldMO47@', 'Madison Okafor434', 'madison_okafor434');
SELECT restore_rollcall_user('leo.miller253@hotmail.com', 'ChillLM82*', 'Leo Miller253', 'leo_miller253');
SELECT restore_rollcall_user('alexandra.smith76@hotmail.com', 'NeonAS26#', 'Alexandra Smith76', 'alexandra_smith76');
SELECT restore_rollcall_user('madison.coleman160@outlook.com', 'EpicMC36#', 'Madison Coleman160', 'madison_coleman160');
SELECT restore_rollcall_user('jacob.wood723@icloud.com', 'FastJW79!', 'Jacob Wood723', 'jacob_wood723');
SELECT restore_rollcall_user('courtney.mitchell886@yahoo.com', 'HappyCM32#', 'Courtney Mitchell886', 'courtney_mitchell886');
SELECT restore_rollcall_user('pedro.jenkins25@yahoo.com', 'NeonPJ18#', 'Pedro Jenkins25', 'pedro_jenkins25');
SELECT restore_rollcall_user('cameron.clark747@outlook.com', 'PeakCC24$', 'Cameron Clark747', 'cameron_clark747');
SELECT restore_rollcall_user('mia.price335@icloud.com', 'BoldMP63$', 'Mia Price335', 'mia_price335');
SELECT restore_rollcall_user('allison.murphy524@icloud.com', 'CoolAM46*', 'Allison Murphy524', 'allison_murphy524');
SELECT restore_rollcall_user('charlotte.hall467@icloud.com', 'WildCH73$', 'Charlotte Hall467', 'charlotte_hall467');
SELECT restore_rollcall_user('chase.robinson468@yahoo.com', 'PeakCR81*', 'Chase Robinson468', 'chase_robinson468');
SELECT restore_rollcall_user('brittany.perez451@gmail.com', 'EpicBP50*', 'Brittany Perez451', 'brittany_perez451');
SELECT restore_rollcall_user('thomas.mitchell478@icloud.com', 'WildTM84!', 'Thomas Mitchell478', 'thomas_mitchell478');
SELECT restore_rollcall_user('victoria.perez345@icloud.com', 'FastVP89*', 'Victoria Perez345', 'victoria_perez345');
SELECT restore_rollcall_user('alexis.evans389@outlook.com', 'EpicAE53$', 'Alexis Evans389', 'alexis_evans389');
SELECT restore_rollcall_user('pedro.gonzalez773@gmail.com', 'HappyPG89@', 'Pedro Gonzalez773', 'pedro_gonzalez773');
SELECT restore_rollcall_user('robert.diaz988@outlook.com', 'NeonRD83$', 'Robert Diaz988', 'robert_diaz988');
SELECT restore_rollcall_user('cassidy.morgan519@outlook.com', 'FreeCM23$', 'Cassidy Morgan519', 'cassidy_morgan519');
SELECT restore_rollcall_user('matthew.nelson584@hotmail.com', 'HappyMN73#', 'Matthew Nelson584', 'matthew_nelson584');
SELECT restore_rollcall_user('cole.allen88@yahoo.com', 'PeakCA40$', 'Cole Allen88', 'cole_allen88');
SELECT restore_rollcall_user('dana.long544@outlook.com', 'PeakDL52#', 'Dana Long544', 'dana_long544');
SELECT restore_rollcall_user('jordan.gomez742@hotmail.com', 'NeonJG39#', 'Jordan Gomez742', 'jordan_gomez742');
SELECT restore_rollcall_user('gavin.sullivan894@gmail.com', 'FreeGS53@', 'Gavin Sullivan894', 'gavin_sullivan894');
SELECT restore_rollcall_user('cole.zhao795@hotmail.com', 'FreeCZ48*', 'Cole Zhao795', 'cole_zhao795');
SELECT restore_rollcall_user('aiden.mitchell299@gmail.com', 'NeonAM99$', 'Aiden Mitchell299', 'aiden_mitchell299');
SELECT restore_rollcall_user('isabella.hill62@yahoo.com', 'ChillIH46$', 'Isabella Hill62', 'isabella_hill62');
SELECT restore_rollcall_user('wesley.butler753@outlook.com', 'BoldWB96*', 'Wesley Butler753', 'wesley_butler753');
SELECT restore_rollcall_user('dylan.parker342@outlook.com', 'WildDP98$', 'Dylan Parker342', 'dylan_parker342');
SELECT restore_rollcall_user('nora.coleman845@gmail.com', 'HappyNC34*', 'Nora Coleman845', 'nora_coleman845');
SELECT restore_rollcall_user('gabrielle.baker319@hotmail.com', 'BoldGB24$', 'Gabrielle Baker319', 'gabrielle_baker319');
SELECT restore_rollcall_user('daniel.howard957@hotmail.com', 'NeonDH48*', 'Daniel Howard957', 'daniel_howard957');
SELECT restore_rollcall_user('alejandro.jones586@icloud.com', 'HappyAJ50$', 'Alejandro Jones586', 'alejandro_jones586');
SELECT restore_rollcall_user('elijah.ruiz539@icloud.com', 'FastER19$', 'Elijah Ruiz539', 'elijah_ruiz539');
SELECT restore_rollcall_user('christina.barnes647@outlook.com', 'WildCB22!', 'Christina Barnes647', 'christina_barnes647');
SELECT restore_rollcall_user('victor.cox422@hotmail.com', 'FastVC20*', 'Victor Cox422', 'victor_cox422');
SELECT restore_rollcall_user('david.murphy307@icloud.com', 'BoldDM59$', 'David Murphy307', 'david_murphy307');
SELECT restore_rollcall_user('serena.howard886@gmail.com', 'NeonSH39*', 'Serena Howard886', 'serena_howard886');
SELECT restore_rollcall_user('jasmine.foster898@outlook.com', 'NeonJF71#', 'Jasmine Foster898', 'jasmine_foster898');
SELECT restore_rollcall_user('madison.richardson378@outlook.com', 'EpicMR23@', 'Madison Richardson378', 'madison_richardson378');
SELECT restore_rollcall_user('eva.cooper312@icloud.com', 'PeakEC27$', 'Eva Cooper312', 'eva_cooper312');
SELECT restore_rollcall_user('matthew.barnes455@icloud.com', 'CoolMB97#', 'Matthew Barnes455', 'matthew_barnes455');
SELECT restore_rollcall_user('demi.anderson250@yahoo.com', 'PeakDA36*', 'Demi Anderson250', 'demi_anderson250');
SELECT restore_rollcall_user('jasmine.coleman16@outlook.com', 'EpicJC12@', 'Jasmine Coleman16', 'jasmine_coleman16');
SELECT restore_rollcall_user('brenda.russell516@yahoo.com', 'PeakBR48$', 'Brenda Russell516', 'brenda_russell516');
SELECT restore_rollcall_user('destiny.cox282@hotmail.com', 'PeakDC47$', 'Destiny Cox282', 'destiny_cox282');
SELECT restore_rollcall_user('alejandro.miller321@icloud.com', 'EpicAM29$', 'Alejandro Miller321', 'alejandro_miller321');
SELECT restore_rollcall_user('genesis.robinson980@hotmail.com', 'WildGR55$', 'Genesis Robinson980', 'genesis_robinson980');
SELECT restore_rollcall_user('eva.zhao232@icloud.com', 'NeonEZ13@', 'Eva Zhao232', 'eva_zhao232');
SELECT restore_rollcall_user('daniel.cox765@hotmail.com', 'WildDC68#', 'Daniel Cox765', 'daniel_cox765');
SELECT restore_rollcall_user('ivan.davis279@icloud.com', 'ChillID66$', 'Ivan Davis279', 'ivan_davis279');
SELECT restore_rollcall_user('dawn.perez47@yahoo.com', 'HappyDP10@', 'Dawn Perez47', 'dawn_perez47');
SELECT restore_rollcall_user('genesis.lopez513@hotmail.com', 'HappyGL65!', 'Genesis Lopez513', 'genesis_lopez513');
SELECT restore_rollcall_user('dion.nguyen448@gmail.com', 'ChillDN61*', 'Dion Nguyen448', 'dion_nguyen448');
SELECT restore_rollcall_user('cassandra.ramirez360@yahoo.com', 'FastCR42@', 'Cassandra Ramirez360', 'cassandra_ramirez360');
SELECT restore_rollcall_user('crystal.taylor155@icloud.com', 'NeonCT45*', 'Crystal Taylor155', 'crystal_taylor155');
SELECT restore_rollcall_user('chloe.long661@gmail.com', 'ChillCL80!', 'Chloe Long661', 'chloe_long661');
SELECT restore_rollcall_user('ben.taylor254@icloud.com', 'PeakBT88@', 'Ben Taylor254', 'ben_taylor254');
SELECT restore_rollcall_user('omar.carter291@outlook.com', 'CoolOC84@', 'Omar Carter291', 'omar_carter291');
SELECT restore_rollcall_user('bianca.lewis317@yahoo.com', 'FreeBL34@', 'Bianca Lewis317', 'bianca_lewis317');
SELECT restore_rollcall_user('jacob.evans45@icloud.com', 'BoldJE66*', 'Jacob Evans45', 'jacob_evans45');
SELECT restore_rollcall_user('jordan.long473@outlook.com', 'PeakJL63@', 'Jordan Long473', 'jordan_long473');
SELECT restore_rollcall_user('maria.nelson851@icloud.com', 'FreeMN54!', 'Maria Nelson851', 'maria_nelson851');
SELECT restore_rollcall_user('elijah.reyes141@gmail.com', 'FastER70$', 'Elijah Reyes141', 'elijah_reyes141');
SELECT restore_rollcall_user('morgan.collins430@hotmail.com', 'CoolMC73*', 'Morgan Collins430', 'morgan_collins430');
SELECT restore_rollcall_user('jenna.torres999@outlook.com', 'PeakJT80!', 'Jenna Torres999', 'jenna_torres999');
SELECT restore_rollcall_user('dana.wood46@outlook.com', 'FastDW97$', 'Dana Wood46', 'dana_wood46');
SELECT restore_rollcall_user('brenda.martinez260@gmail.com', 'EpicBM16#', 'Brenda Martinez260', 'brenda_martinez260');
SELECT restore_rollcall_user('owen.evans377@hotmail.com', 'WildOE20$', 'Owen Evans377', 'owen_evans377');
SELECT restore_rollcall_user('jake.ward458@gmail.com', 'NeonJW91!', 'Jake Ward458', 'jake_ward458');
SELECT restore_rollcall_user('brooklyn.cox130@gmail.com', 'EpicBC56$', 'Brooklyn Cox130', 'brooklyn_cox130');
SELECT restore_rollcall_user('logan.coleman512@hotmail.com', 'PeakLC25#', 'Logan Coleman512', 'logan_coleman512');
SELECT restore_rollcall_user('david.nelson90@outlook.com', 'PeakDN79#', 'David Nelson90', 'david_nelson90');
SELECT restore_rollcall_user('devon.campbell408@icloud.com', 'WildDC83!', 'Devon Campbell408', 'devon_campbell408');
SELECT restore_rollcall_user('gavin.castillo187@yahoo.com', 'HappyGC25*', 'Gavin Castillo187', 'gavin_castillo187');
SELECT restore_rollcall_user('diana.harris282@yahoo.com', 'CoolDH74@', 'Diana Harris282', 'diana_harris282');
SELECT restore_rollcall_user('justin.patel633@gmail.com', 'PeakJP47#', 'Justin Patel633', 'justin_patel633');
SELECT restore_rollcall_user('alexis.garcia321@outlook.com', 'EpicAG75*', 'Alexis Garcia321', 'alexis_garcia321');
SELECT restore_rollcall_user('chase.jackson255@yahoo.com', 'EpicCJ34@', 'Chase Jackson255', 'chase_jackson255');
SELECT restore_rollcall_user('liam.gomez50@gmail.com', 'FreeLG46*', 'Liam Gomez50', 'liam_gomez50');
SELECT restore_rollcall_user('sofia.bennett200@outlook.com', 'PeakSB67*', 'Sofia Bennett200', 'sofia_bennett200');
SELECT restore_rollcall_user('owen.robinson204@hotmail.com', 'HappyOR15!', 'Owen Robinson204', 'owen_robinson204');
SELECT restore_rollcall_user('olivia.scott403@hotmail.com', 'PeakOS75*', 'Olivia Scott403', 'olivia_scott403');
SELECT restore_rollcall_user('brianna.sanchez991@hotmail.com', 'ChillBS71@', 'Brianna Sanchez991', 'brianna_sanchez991');
SELECT restore_rollcall_user('jessica.anderson429@yahoo.com', 'BoldJA62*', 'Jessica Anderson429', 'jessica_anderson429');
SELECT restore_rollcall_user('nicole.edwards351@hotmail.com', 'NeonNE88$', 'Nicole Edwards351', 'nicole_edwards351');
SELECT restore_rollcall_user('ashley.johnson574@outlook.com', 'PeakAJ58$', 'Ashley Johnson574', 'ashley_johnson574');
SELECT restore_rollcall_user('hannah.clark249@gmail.com', 'BoldHC16!', 'Hannah Clark249', 'hannah_clark249');
SELECT restore_rollcall_user('angel.patterson329@outlook.com', 'ChillAP39*', 'Angel Patterson329', 'angel_patterson329');
SELECT restore_rollcall_user('cynthia.sanders292@icloud.com', 'FastCS74$', 'Cynthia Sanders292', 'cynthia_sanders292');
SELECT restore_rollcall_user('owen.mensah691@yahoo.com', 'WildOM64*', 'Owen Mensah691', 'owen_mensah691');
SELECT restore_rollcall_user('zoe.young310@hotmail.com', 'BoldZY17!', 'Zoe Young310', 'zoe_young310');
SELECT restore_rollcall_user('ivan.nguyen719@hotmail.com', 'PeakIN95@', 'Ivan Nguyen719', 'ivan_nguyen719');
SELECT restore_rollcall_user('dakota.richardson336@hotmail.com', 'BoldDR84$', 'Dakota Richardson336', 'dakota_richardson336');
SELECT restore_rollcall_user('alejandro.rodriguez474@outlook.com', 'HappyAR37*', 'Alejandro Rodriguez474', 'alejandro_rodriguez474');
SELECT restore_rollcall_user('amanda.barnes185@yahoo.com', 'WildAB67$', 'Amanda Barnes185', 'amanda_barnes185');
SELECT restore_rollcall_user('alexis.turner545@icloud.com', 'FreeAT54@', 'Alexis Turner545', 'alexis_turner545');
SELECT restore_rollcall_user('liam.garcia609@gmail.com', 'HappyLG41!', 'Liam Garcia609', 'liam_garcia609');
SELECT restore_rollcall_user('leo.james227@icloud.com', 'PeakLJ85@', 'Leo James227', 'leo_james227');
SELECT restore_rollcall_user('tanner.cruz189@hotmail.com', 'BoldTC48@', 'Tanner Cruz189', 'tanner_cruz189');
SELECT restore_rollcall_user('christian.williams275@icloud.com', 'ChillCW95*', 'Christian Williams275', 'christian_williams275');
SELECT restore_rollcall_user('anthony.hall938@yahoo.com', 'WildAH69*', 'Anthony Hall938', 'anthony_hall938');
SELECT restore_rollcall_user('robert.johnson577@yahoo.com', 'NeonRJ80*', 'Robert Johnson577', 'robert_johnson577');
SELECT restore_rollcall_user('claudia.thomas782@icloud.com', 'FastCT55@', 'Claudia Thomas782', 'claudia_thomas782');
SELECT restore_rollcall_user('derek.vasquez423@yahoo.com', 'FastDV11@', 'Derek Vasquez423', 'derek_vasquez423');
SELECT restore_rollcall_user('christian.hughes833@icloud.com', 'CoolCH77@', 'Christian Hughes833', 'christian_hughes833');
SELECT restore_rollcall_user('alexandra.rodriguez308@gmail.com', 'WildAR80$', 'Alexandra Rodriguez308', 'alexandra_rodriguez308');
SELECT restore_rollcall_user('cassandra.bell923@hotmail.com', 'HappyCB19#', 'Cassandra Bell923', 'cassandra_bell923');
SELECT restore_rollcall_user('sara.young513@outlook.com', 'CoolSY53*', 'Sara Young513', 'sara_young513');
SELECT restore_rollcall_user('cody.lopez697@hotmail.com', 'ChillCL47@', 'Cody Lopez697', 'cody_lopez697');
SELECT restore_rollcall_user('dylan.adams369@outlook.com', 'WildDA67*', 'Dylan Adams369', 'dylan_adams369');
SELECT restore_rollcall_user('taylor.martin927@yahoo.com', 'WildTM31@', 'Taylor Martin927', 'taylor_martin927');
SELECT restore_rollcall_user('tiffany.james370@outlook.com', 'FreeTJ86*', 'Tiffany James370', 'tiffany_james370');
SELECT restore_rollcall_user('omar.murphy836@hotmail.com', 'EpicOM87@', 'Omar Murphy836', 'omar_murphy836');
SELECT restore_rollcall_user('eva.rodriguez559@yahoo.com', 'BoldER66#', 'Eva Rodriguez559', 'eva_rodriguez559');
SELECT restore_rollcall_user('danny.miller946@icloud.com', 'PeakDM86!', 'Danny Miller946', 'danny_miller946');
SELECT restore_rollcall_user('axel.carter523@hotmail.com', 'EpicAC60$', 'Axel Carter523', 'axel_carter523');
SELECT restore_rollcall_user('pedro.jenkins804@yahoo.com', 'FreePJ22$', 'Pedro Jenkins804', 'pedro_jenkins804');
SELECT restore_rollcall_user('emma.turner529@yahoo.com', 'PeakET64$', 'Emma Turner529', 'emma_turner529');
SELECT restore_rollcall_user('serena.baker607@icloud.com', 'BoldSB36#', 'Serena Baker607', 'serena_baker607');
SELECT restore_rollcall_user('cassandra.sullivan626@icloud.com', 'FreeCS89@', 'Cassandra Sullivan626', 'cassandra_sullivan626');
SELECT restore_rollcall_user('tiffany.sanchez393@icloud.com', 'PeakTS98@', 'Tiffany Sanchez393', 'tiffany_sanchez393');
SELECT restore_rollcall_user('ariana.cooper987@hotmail.com', 'FreeAC63$', 'Ariana Cooper987', 'ariana_cooper987');
SELECT restore_rollcall_user('alexandra.rodriguez524@gmail.com', 'EpicAR79!', 'Alexandra Rodriguez524', 'alexandra_rodriguez524');
SELECT restore_rollcall_user('wesley.collins831@hotmail.com', 'ChillWC90$', 'Wesley Collins831', 'wesley_collins831');
SELECT restore_rollcall_user('demi.richardson721@outlook.com', 'PeakDR96!', 'Demi Richardson721', 'demi_richardson721');
SELECT restore_rollcall_user('logan.cox780@icloud.com', 'ChillLC90#', 'Logan Cox780', 'logan_cox780');
SELECT restore_rollcall_user('robert.nguyen596@gmail.com', 'EpicRN18*', 'Robert Nguyen596', 'robert_nguyen596');
SELECT restore_rollcall_user('chase.bell17@gmail.com', 'FreeCB10$', 'Chase Bell17', 'chase_bell17');
SELECT restore_rollcall_user('dylan.thomas85@outlook.com', 'WildDT90#', 'Dylan Thomas85', 'dylan_thomas85');
SELECT restore_rollcall_user('brian.walker9@outlook.com', 'FastBW71!', 'Brian Walker9', 'brian_walker9');
SELECT restore_rollcall_user('grace.taylor544@hotmail.com', 'FreeGT54@', 'Grace Taylor544', 'grace_taylor544');
SELECT restore_rollcall_user('pedro.morgan254@outlook.com', 'ChillPM87#', 'Pedro Morgan254', 'pedro_morgan254');
SELECT restore_rollcall_user('austin.martin512@hotmail.com', 'EpicAM50@', 'Austin Martin512', 'austin_martin512');
SELECT restore_rollcall_user('darryl.brown221@gmail.com', 'NeonDB90*', 'Darryl Brown221', 'darryl_brown221');
SELECT restore_rollcall_user('diana.ramirez550@outlook.com', 'CoolDR49$', 'Diana Ramirez550', 'diana_ramirez550');
SELECT restore_rollcall_user('finn.allen168@icloud.com', 'NeonFA31#', 'Finn Allen168', 'finn_allen168');
SELECT restore_rollcall_user('maria.reyes730@hotmail.com', 'EpicMR17$', 'Maria Reyes730', 'maria_reyes730');
SELECT restore_rollcall_user('riley.martin954@gmail.com', 'EpicRM41$', 'Riley Martin954', 'riley_martin954');
SELECT restore_rollcall_user('dominic.roberts378@yahoo.com', 'ChillDR41$', 'Dominic Roberts378', 'dominic_roberts378');
SELECT restore_rollcall_user('axel.kelly870@outlook.com', 'WildAK72!', 'Axel Kelly870', 'axel_kelly870');
SELECT restore_rollcall_user('derek.russell446@yahoo.com', 'NeonDR50$', 'Derek Russell446', 'derek_russell446');
SELECT restore_rollcall_user('ivan.clark478@outlook.com', 'PeakIC55@', 'Ivan Clark478', 'ivan_clark478');
SELECT restore_rollcall_user('kevin.castillo94@yahoo.com', 'HappyKC96#', 'Kevin Castillo94', 'kevin_castillo94');
SELECT restore_rollcall_user('elena.ortiz125@gmail.com', 'FastEO35$', 'Elena Ortiz125', 'elena_ortiz125');
SELECT restore_rollcall_user('dylan.ruiz44@icloud.com', 'WildDR60$', 'Dylan Ruiz44', 'dylan_ruiz44');
SELECT restore_rollcall_user('matthew.nelson629@hotmail.com', 'NeonMN73$', 'Matthew Nelson629', 'matthew_nelson629');
SELECT restore_rollcall_user('anthony.rivera935@hotmail.com', 'FastAR13#', 'Anthony Rivera935', 'anthony_rivera935');
SELECT restore_rollcall_user('liam.hill783@yahoo.com', 'FastLH32@', 'Liam Hill783', 'liam_hill783');
SELECT restore_rollcall_user('jasmine.perez58@yahoo.com', 'PeakJP71!', 'Jasmine Perez58', 'jasmine_perez58');
SELECT restore_rollcall_user('ethan.ruiz984@gmail.com', 'WildER85!', 'Ethan Ruiz984', 'ethan_ruiz984');
SELECT restore_rollcall_user('lara.torres388@outlook.com', 'HappyLT99*', 'Lara Torres388', 'lara_torres388');
SELECT restore_rollcall_user('derek.griffin172@gmail.com', 'NeonDG36@', 'Derek Griffin172', 'derek_griffin172');
SELECT restore_rollcall_user('jake.mitchell360@hotmail.com', 'FreeJM83@', 'Jake Mitchell360', 'jake_mitchell360');
SELECT restore_rollcall_user('david.kim165@gmail.com', 'FreeDK13$', 'David Kim165', 'david_kim165');
SELECT restore_rollcall_user('leo.carter586@hotmail.com', 'HappyLC56!', 'Leo Carter586', 'leo_carter586');
SELECT restore_rollcall_user('diana.parker804@icloud.com', 'NeonDP21*', 'Diana Parker804', 'diana_parker804');
SELECT restore_rollcall_user('lara.reyes64@yahoo.com', 'PeakLR62*', 'Lara Reyes64', 'lara_reyes64');
SELECT restore_rollcall_user('mia.butler515@hotmail.com', 'FreeMB32@', 'Mia Butler515', 'mia_butler515');
SELECT restore_rollcall_user('dominic.martin566@outlook.com', 'HappyDM99*', 'Dominic Martin566', 'dominic_martin566');
SELECT restore_rollcall_user('christian.king393@icloud.com', 'FastCK45$', 'Christian King393', 'christian_king393');
SELECT restore_rollcall_user('chase.wright919@outlook.com', 'NeonCW49#', 'Chase Wright919', 'chase_wright919');
SELECT restore_rollcall_user('tanner.wood889@outlook.com', 'CoolTW49*', 'Tanner Wood889', 'tanner_wood889');
SELECT restore_rollcall_user('ricky.watson378@icloud.com', 'CoolRW97!', 'Ricky Watson378', 'ricky_watson378');
SELECT restore_rollcall_user('patrick.davis292@gmail.com', 'FastPD83@', 'Patrick Davis292', 'patrick_davis292');
SELECT restore_rollcall_user('lucas.sanders434@icloud.com', 'BoldLS69#', 'Lucas Sanders434', 'lucas_sanders434');
SELECT restore_rollcall_user('mia.walker66@outlook.com', 'NeonMW43#', 'Mia Walker66', 'mia_walker66');
SELECT restore_rollcall_user('hannah.williams303@outlook.com', 'WildHW14*', 'Hannah Williams303', 'hannah_williams303');
SELECT restore_rollcall_user('james.reyes301@gmail.com', 'NeonJR81@', 'James Reyes301', 'james_reyes301');
SELECT restore_rollcall_user('chris.sullivan967@hotmail.com', 'PeakCS25$', 'Chris Sullivan967', 'chris_sullivan967');
SELECT restore_rollcall_user('nicole.white500@outlook.com', 'HappyNW10$', 'Nicole White500', 'nicole_white500');
SELECT restore_rollcall_user('sophia.morgan5@gmail.com', 'HappySM51*', 'Sophia Morgan5', 'sophia_morgan5');
SELECT restore_rollcall_user('patrick.jenkins393@hotmail.com', 'HappyPJ48#', 'Patrick Jenkins393', 'patrick_jenkins393');
SELECT restore_rollcall_user('sophia.anderson745@yahoo.com', 'ChillSA74@', 'Sophia Anderson745', 'sophia_anderson745');
SELECT restore_rollcall_user('demi.bennett50@gmail.com', 'WildDB25*', 'Demi Bennett50', 'demi_bennett50');
SELECT restore_rollcall_user('morgan.moore277@hotmail.com', 'CoolMM75*', 'Morgan Moore277', 'morgan_moore277');
SELECT restore_rollcall_user('brittany.foster303@yahoo.com', 'BoldBF98$', 'Brittany Foster303', 'brittany_foster303');
SELECT restore_rollcall_user('luis.taylor304@outlook.com', 'CoolLT32!', 'Luis Taylor304', 'luis_taylor304');
SELECT restore_rollcall_user('dylan.long117@icloud.com', 'NeonDL59$', 'Dylan Long117', 'dylan_long117');
SELECT restore_rollcall_user('jayden.scott627@gmail.com', 'FreeJS24$', 'Jayden Scott627', 'jayden_scott627');
SELECT restore_rollcall_user('victor.thompson355@icloud.com', 'ChillVT16!', 'Victor Thompson355', 'victor_thompson355');
SELECT restore_rollcall_user('claudia.taylor837@yahoo.com', 'ChillCT67!', 'Claudia Taylor837', 'claudia_taylor837');
SELECT restore_rollcall_user('bianca.robinson974@outlook.com', 'BoldBR68#', 'Bianca Robinson974', 'bianca_robinson974');
SELECT restore_rollcall_user('paige.lee535@outlook.com', 'FreePL27$', 'Paige Lee535', 'paige_lee535');
SELECT restore_rollcall_user('alexandra.morales111@icloud.com', 'ChillAM25$', 'Alexandra Morales111', 'alexandra_morales111');
SELECT restore_rollcall_user('gavin.clark517@icloud.com', 'BoldGC45$', 'Gavin Clark517', 'gavin_clark517');
SELECT restore_rollcall_user('patrick.turner516@hotmail.com', 'EpicPT81$', 'Patrick Turner516', 'patrick_turner516');
SELECT restore_rollcall_user('santiago.cox205@outlook.com', 'NeonSC28!', 'Santiago Cox205', 'santiago_cox205');
SELECT restore_rollcall_user('leo.ramirez949@icloud.com', 'EpicLR80!', 'Leo Ramirez949', 'leo_ramirez949');
SELECT restore_rollcall_user('darryl.rivera302@icloud.com', 'CoolDR33@', 'Darryl Rivera302', 'darryl_rivera302');
SELECT restore_rollcall_user('amara.kelly41@yahoo.com', 'ChillAK94#', 'Amara Kelly41', 'amara_kelly41');
SELECT restore_rollcall_user('ben.davis550@icloud.com', 'BoldBD94#', 'Ben Davis550', 'ben_davis550');
SELECT restore_rollcall_user('carlos.walker938@gmail.com', 'PeakCW46!', 'Carlos Walker938', 'carlos_walker938');
SELECT restore_rollcall_user('damian.garcia856@gmail.com', 'WildDG92!', 'Damian Garcia856', 'damian_garcia856');
SELECT restore_rollcall_user('dallas.morales418@icloud.com', 'WildDM65#', 'Dallas Morales418', 'dallas_morales418');
SELECT restore_rollcall_user('danny.bell951@hotmail.com', 'NeonDB87!', 'Danny Bell951', 'danny_bell951');
SELECT restore_rollcall_user('jack.richardson765@icloud.com', 'NeonJR96#', 'Jack Richardson765', 'jack_richardson765');
SELECT restore_rollcall_user('kayla.mitchell165@yahoo.com', 'NeonKM34!', 'Kayla Mitchell165', 'kayla_mitchell165');
SELECT restore_rollcall_user('michael.torres101@yahoo.com', 'EpicMT26@', 'Michael Torres101', 'michael_torres101');
SELECT restore_rollcall_user('omar.scott157@hotmail.com', 'WildOS31!', 'Omar Scott157', 'omar_scott157');
SELECT restore_rollcall_user('ariana.roberts662@hotmail.com', 'FastAR78@', 'Ariana Roberts662', 'ariana_roberts662');
SELECT restore_rollcall_user('dana.ross218@gmail.com', 'FreeDR93@', 'Dana Ross218', 'dana_ross218');
SELECT restore_rollcall_user('diamond.walker144@icloud.com', 'ChillDW82@', 'Diamond Walker144', 'diamond_walker144');
SELECT restore_rollcall_user('carlos.torres930@outlook.com', 'FreeCT15!', 'Carlos Torres930', 'carlos_torres930');
SELECT restore_rollcall_user('lara.reed837@outlook.com', 'FreeLR87!', 'Lara Reed837', 'lara_reed837');
SELECT restore_rollcall_user('jack.lewis425@outlook.com', 'FreeJL36*', 'Jack Lewis425', 'jack_lewis425');
SELECT restore_rollcall_user('grace.stewart913@hotmail.com', 'FastGS43@', 'Grace Stewart913', 'grace_stewart913');
SELECT restore_rollcall_user('denise.cox639@hotmail.com', 'EpicDC68*', 'Denise Cox639', 'denise_cox639');
SELECT restore_rollcall_user('jason.parker516@gmail.com', 'ChillJP79!', 'Jason Parker516', 'jason_parker516');
SELECT restore_rollcall_user('anthony.patel291@hotmail.com', 'BoldAP10!', 'Anthony Patel291', 'anthony_patel291');
SELECT restore_rollcall_user('luna.vega579@outlook.com', 'BoldLV62*', 'Luna Vega579', 'luna_vega579');
SELECT restore_rollcall_user('finn.wright802@yahoo.com', 'EpicFW80*', 'Finn Wright802', 'finn_wright802');
SELECT restore_rollcall_user('damian.hernandez82@hotmail.com', 'WildDH88*', 'Damian Hernandez82', 'damian_hernandez82');
SELECT restore_rollcall_user('axel.foster200@gmail.com', 'FastAF96!', 'Axel Foster200', 'axel_foster200');
SELECT restore_rollcall_user('brian.allen563@outlook.com', 'BoldBA87@', 'Brian Allen563', 'brian_allen563');
SELECT restore_rollcall_user('christian.vasquez711@icloud.com', 'FreeCV41#', 'Christian Vasquez711', 'christian_vasquez711');
SELECT restore_rollcall_user('madison.hall409@outlook.com', 'FreeMH50#', 'Madison Hall409', 'madison_hall409');
SELECT restore_rollcall_user('joshua.griffin212@yahoo.com', 'ChillJG55@', 'Joshua Griffin212', 'joshua_griffin212');
SELECT restore_rollcall_user('dallas.howard783@hotmail.com', 'ChillDH26!', 'Dallas Howard783', 'dallas_howard783');
SELECT restore_rollcall_user('brian.nguyen13@yahoo.com', 'CoolBN51#', 'Brian Nguyen13', 'brian_nguyen13');
SELECT restore_rollcall_user('justin.moore875@icloud.com', 'ChillJM26*', 'Justin Moore875', 'justin_moore875');
SELECT restore_rollcall_user('angel.delacroix432@icloud.com', 'PeakAD78#', 'Angel Delacroix432', 'angel_delacroix432');
SELECT restore_rollcall_user('luis.parker763@outlook.com', 'PeakLP81#', 'Luis Parker763', 'luis_parker763');
SELECT restore_rollcall_user('bianca.perez391@hotmail.com', 'FastBP31#', 'Bianca Perez391', 'bianca_perez391');
SELECT restore_rollcall_user('michael.watson278@icloud.com', 'PeakMW67$', 'Michael Watson278', 'michael_watson278');
SELECT restore_rollcall_user('justin.diaz98@gmail.com', 'HappyJD13$', 'Justin Diaz98', 'justin_diaz98');
SELECT restore_rollcall_user('maya.murphy540@yahoo.com', 'EpicMM70$', 'Maya Murphy540', 'maya_murphy540');
SELECT restore_rollcall_user('dominic.murphy423@outlook.com', 'HappyDM10*', 'Dominic Murphy423', 'dominic_murphy423');
SELECT restore_rollcall_user('claudia.long904@hotmail.com', 'BoldCL30$', 'Claudia Long904', 'claudia_long904');
SELECT restore_rollcall_user('michael.coleman279@hotmail.com', 'EpicMC12@', 'Michael Coleman279', 'michael_coleman279');
SELECT restore_rollcall_user('gavin.white239@gmail.com', 'FreeGW37#', 'Gavin White239', 'gavin_white239');
SELECT restore_rollcall_user('marcus.kim557@icloud.com', 'NeonMK58!', 'Marcus Kim557', 'marcus_kim557');
SELECT restore_rollcall_user('jose.nguyen682@yahoo.com', 'NeonJN51@', 'Jose Nguyen682', 'jose_nguyen682');
SELECT restore_rollcall_user('leo.sullivan16@yahoo.com', 'WildLS41!', 'Leo Sullivan16', 'leo_sullivan16');
SELECT restore_rollcall_user('rebecca.taylor811@gmail.com', 'BoldRT50*', 'Rebecca Taylor811', 'rebecca_taylor811');
SELECT restore_rollcall_user('ariana.watson302@hotmail.com', 'ChillAW33*', 'Ariana Watson302', 'ariana_watson302');
SELECT restore_rollcall_user('miguel.vasquez376@icloud.com', 'WildMV33!', 'Miguel Vasquez376', 'miguel_vasquez376');
SELECT restore_rollcall_user('nora.mitchell99@hotmail.com', 'FastNM32!', 'Nora Mitchell99', 'nora_mitchell99');
SELECT restore_rollcall_user('ashley.reyes51@outlook.com', 'CoolAR11@', 'Ashley Reyes51', 'ashley_reyes51');
SELECT restore_rollcall_user('david.castillo968@yahoo.com', 'PeakDC59@', 'David Castillo968', 'david_castillo968');
SELECT restore_rollcall_user('emma.patel691@icloud.com', 'CoolEP31@', 'Emma Patel691', 'emma_patel691');
SELECT restore_rollcall_user('ryan.mitchell624@yahoo.com', 'PeakRM42#', 'Ryan Mitchell624', 'ryan_mitchell624');
SELECT restore_rollcall_user('mason.roberts585@hotmail.com', 'HappyMR68#', 'Mason Roberts585', 'mason_roberts585');
SELECT restore_rollcall_user('mia.campbell583@yahoo.com', 'FreeMC32$', 'Mia Campbell583', 'mia_campbell583');
SELECT restore_rollcall_user('dennis.allen313@hotmail.com', 'FastDA51*', 'Dennis Allen313', 'dennis_allen313');
SELECT restore_rollcall_user('genesis.kim586@gmail.com', 'CoolGK61*', 'Genesis Kim586', 'genesis_kim586');
SELECT restore_rollcall_user('lily.bryant332@hotmail.com', 'WildLB56#', 'Lily Bryant332', 'lily_bryant332');
SELECT restore_rollcall_user('diamond.morales452@gmail.com', 'EpicDM29!', 'Diamond Morales452', 'diamond_morales452');
SELECT restore_rollcall_user('ethan.jenkins24@outlook.com', 'BoldEJ36*', 'Ethan Jenkins24', 'ethan_jenkins24');
SELECT restore_rollcall_user('luis.diaz206@hotmail.com', 'HappyLD18$', 'Luis Diaz206', 'luis_diaz206');
SELECT restore_rollcall_user('bianca.watson497@hotmail.com', 'FreeBW81!', 'Bianca Watson497', 'bianca_watson497');
SELECT restore_rollcall_user('blake.king641@outlook.com', 'NeonBK17#', 'Blake King641', 'blake_king641');
SELECT restore_rollcall_user('thomas.griffin437@outlook.com', 'FastTG36@', 'Thomas Griffin437', 'thomas_griffin437');
SELECT restore_rollcall_user('noah.brown972@gmail.com', 'FastNB13#', 'Noah Brown972', 'noah_brown972');
SELECT restore_rollcall_user('destiny.rodriguez237@gmail.com', 'FreeDR27*', 'Destiny Rodriguez237', 'destiny_rodriguez237');
SELECT restore_rollcall_user('taylor.gonzalez68@yahoo.com', 'ChillTG72#', 'Taylor Gonzalez68', 'taylor_gonzalez68');
SELECT restore_rollcall_user('alejandro.morales532@hotmail.com', 'HappyAM81$', 'Alejandro Morales532', 'alejandro_morales532');
SELECT restore_rollcall_user('miguel.scott926@yahoo.com', 'FreeMS21*', 'Miguel Scott926', 'miguel_scott926');
SELECT restore_rollcall_user('brianna.edwards919@yahoo.com', 'NeonBE51@', 'Brianna Edwards919', 'brianna_edwards919');
SELECT restore_rollcall_user('samantha.roberts787@yahoo.com', 'FastSR30@', 'Samantha Roberts787', 'samantha_roberts787');
SELECT restore_rollcall_user('melissa.stewart921@yahoo.com', 'ChillMS42!', 'Melissa Stewart921', 'melissa_stewart921');
SELECT restore_rollcall_user('lily.roberts840@yahoo.com', 'EpicLR14@', 'Lily Roberts840', 'lily_roberts840');
SELECT restore_rollcall_user('alejandro.wright954@gmail.com', 'EpicAW58!', 'Alejandro Wright954', 'alejandro_wright954');
SELECT restore_rollcall_user('justin.scott586@hotmail.com', 'ChillJS46$', 'Justin Scott586', 'justin_scott586');
SELECT restore_rollcall_user('austin.delacroix726@outlook.com', 'CoolAD13$', 'Austin Delacroix726', 'austin_delacroix726');
SELECT restore_rollcall_user('maya.harris308@hotmail.com', 'CoolMH97#', 'Maya Harris308', 'maya_harris308');
SELECT restore_rollcall_user('antonio.cruz918@outlook.com', 'WildAC17*', 'Antonio Cruz918', 'antonio_cruz918');
SELECT restore_rollcall_user('rachel.brown861@gmail.com', 'PeakRB31*', 'Rachel Brown861', 'rachel_brown861');
SELECT restore_rollcall_user('morgan.gomez180@gmail.com', 'BoldMG21$', 'Morgan Gomez180', 'morgan_gomez180');
SELECT restore_rollcall_user('julia.williams397@hotmail.com', 'HappyJW97*', 'Julia Williams397', 'julia_williams397');
SELECT restore_rollcall_user('cassidy.johnson280@yahoo.com', 'CoolCJ11*', 'Cassidy Johnson280', 'cassidy_johnson280');
SELECT restore_rollcall_user('david.jenkins455@gmail.com', 'FreeDJ96!', 'David Jenkins455', 'david_jenkins455');
SELECT restore_rollcall_user('diamond.lee838@yahoo.com', 'FreeDL82@', 'Diamond Lee838', 'diamond_lee838');
SELECT restore_rollcall_user('amanda.green882@hotmail.com', 'WildAG33#', 'Amanda Green882', 'amanda_green882');
SELECT restore_rollcall_user('maya.patel131@hotmail.com', 'CoolMP51*', 'Maya Patel131', 'maya_patel131');
SELECT restore_rollcall_user('antonio.martin214@hotmail.com', 'PeakAM98@', 'Antonio Martin214', 'antonio_martin214');
SELECT restore_rollcall_user('eva.russell569@gmail.com', 'NeonER61!', 'Eva Russell569', 'eva_russell569');
SELECT restore_rollcall_user('hunter.thompson545@outlook.com', 'ChillHT67@', 'Hunter Thompson545', 'hunter_thompson545');
SELECT restore_rollcall_user('patrick.campbell627@hotmail.com', 'FastPC47!', 'Patrick Campbell627', 'patrick_campbell627');
SELECT restore_rollcall_user('noah.white391@icloud.com', 'FastNW70@', 'Noah White391', 'noah_white391');
SELECT restore_rollcall_user('grace.allen148@icloud.com', 'CoolGA27$', 'Grace Allen148', 'grace_allen148');
SELECT restore_rollcall_user('leo.white421@hotmail.com', 'ChillLW71#', 'Leo White421', 'leo_white421');
SELECT restore_rollcall_user('allison.reed912@hotmail.com', 'CoolAR97*', 'Allison Reed912', 'allison_reed912');
SELECT restore_rollcall_user('tiffany.lee172@gmail.com', 'NeonTL17$', 'Tiffany Lee172', 'tiffany_lee172');
SELECT restore_rollcall_user('matthew.harris282@outlook.com', 'FastMH85@', 'Matthew Harris282', 'matthew_harris282');
SELECT restore_rollcall_user('diego.cox771@icloud.com', 'FreeDC91@', 'Diego Cox771', 'diego_cox771');
SELECT restore_rollcall_user('jake.ortiz309@icloud.com', 'WildJO70#', 'Jake Ortiz309', 'jake_ortiz309');
SELECT restore_rollcall_user('cassandra.walker940@hotmail.com', 'ChillCW93#', 'Cassandra Walker940', 'cassandra_walker940');
SELECT restore_rollcall_user('nicole.roberts852@gmail.com', 'CoolNR97$', 'Nicole Roberts852', 'nicole_roberts852');
SELECT restore_rollcall_user('denise.sullivan89@hotmail.com', 'ChillDS33!', 'Denise Sullivan89', 'denise_sullivan89');
SELECT restore_rollcall_user('luis.davis796@gmail.com', 'EpicLD17#', 'Luis Davis796', 'luis_davis796');
SELECT restore_rollcall_user('kevin.scott733@outlook.com', 'ChillKS42$', 'Kevin Scott733', 'kevin_scott733');
SELECT restore_rollcall_user('savannah.hill927@icloud.com', 'FreeSH71$', 'Savannah Hill927', 'savannah_hill927');
SELECT restore_rollcall_user('sofia.brooks548@outlook.com', 'NeonSB92@', 'Sofia Brooks548', 'sofia_brooks548');
SELECT restore_rollcall_user('ariana.butler144@gmail.com', 'ChillAB40$', 'Ariana Butler144', 'ariana_butler144');
SELECT restore_rollcall_user('carlos.miller827@hotmail.com', 'PeakCM29*', 'Carlos Miller827', 'carlos_miller827');
SELECT restore_rollcall_user('dion.bell15@yahoo.com', 'CoolDB68*', 'Dion Bell15', 'dion_bell15');
SELECT restore_rollcall_user('damian.baptiste346@icloud.com', 'ChillDB79@', 'Damian Baptiste346', 'damian_baptiste346');
SELECT restore_rollcall_user('cody.diaz948@hotmail.com', 'ChillCD58@', 'Cody Diaz948', 'cody_diaz948');
SELECT restore_rollcall_user('dawn.hughes709@yahoo.com', 'NeonDH76$', 'Dawn Hughes709', 'dawn_hughes709');
SELECT restore_rollcall_user('finn.reyes884@hotmail.com', 'BoldFR45!', 'Finn Reyes884', 'finn_reyes884');
SELECT restore_rollcall_user('riley.hughes258@outlook.com', 'CoolRH16*', 'Riley Hughes258', 'riley_hughes258');
SELECT restore_rollcall_user('dawn.ross204@outlook.com', 'EpicDR39!', 'Dawn Ross204', 'dawn_ross204');
SELECT restore_rollcall_user('danny.perez149@yahoo.com', 'WildDP57@', 'Danny Perez149', 'danny_perez149');
SELECT restore_rollcall_user('allison.nguyen779@outlook.com', 'ChillAN30*', 'Allison Nguyen779', 'allison_nguyen779');
SELECT restore_rollcall_user('logan.hall594@yahoo.com', 'HappyLH63!', 'Logan Hall594', 'logan_hall594');
SELECT restore_rollcall_user('elijah.nelson86@hotmail.com', 'BoldEN26#', 'Elijah Nelson86', 'elijah_nelson86');
SELECT restore_rollcall_user('jacob.watson766@hotmail.com', 'FastJW61@', 'Jacob Watson766', 'jacob_watson766');
SELECT restore_rollcall_user('miguel.morgan590@yahoo.com', 'HappyMM75#', 'Miguel Morgan590', 'miguel_morgan590');
SELECT restore_rollcall_user('christina.coleman893@yahoo.com', 'EpicCC44*', 'Christina Coleman893', 'christina_coleman893');
SELECT restore_rollcall_user('adrian.smith193@icloud.com', 'FastAS46!', 'Adrian Smith193', 'adrian_smith193');
SELECT restore_rollcall_user('julia.reed427@hotmail.com', 'EpicJR63$', 'Julia Reed427', 'julia_reed427');
SELECT restore_rollcall_user('taylor.ross498@hotmail.com', 'NeonTR82@', 'Taylor Ross498', 'taylor_ross498');
SELECT restore_rollcall_user('christian.hughes860@yahoo.com', 'CoolCH15#', 'Christian Hughes860', 'christian_hughes860');
SELECT restore_rollcall_user('ryan.nelson547@outlook.com', 'FreeRN28$', 'Ryan Nelson547', 'ryan_nelson547');
SELECT restore_rollcall_user('hannah.turner316@gmail.com', 'BoldHT67#', 'Hannah Turner316', 'hannah_turner316');
SELECT restore_rollcall_user('diego.richardson525@icloud.com', 'EpicDR87*', 'Diego Richardson525', 'diego_richardson525');
SELECT restore_rollcall_user('nathan.nelson221@icloud.com', 'FreeNN46@', 'Nathan Nelson221', 'nathan_nelson221');
SELECT restore_rollcall_user('amara.mitchell180@hotmail.com', 'ChillAM27@', 'Amara Mitchell180', 'amara_mitchell180');
SELECT restore_rollcall_user('austin.robinson28@gmail.com', 'NeonAR91$', 'Austin Robinson28', 'austin_robinson28');
SELECT restore_rollcall_user('brooklyn.collins994@gmail.com', 'ChillBC65#', 'Brooklyn Collins994', 'brooklyn_collins994');
SELECT restore_rollcall_user('grace.lee280@outlook.com', 'EpicGL16#', 'Grace Lee280', 'grace_lee280');
SELECT restore_rollcall_user('elena.sanchez331@outlook.com', 'EpicES22*', 'Elena Sanchez331', 'elena_sanchez331');
SELECT restore_rollcall_user('kevin.cruz852@yahoo.com', 'CoolKC24@', 'Kevin Cruz852', 'kevin_cruz852');
SELECT restore_rollcall_user('gavin.vega315@yahoo.com', 'CoolGV64!', 'Gavin Vega315', 'gavin_vega315');
SELECT restore_rollcall_user('amanda.collins68@outlook.com', 'CoolAC87@', 'Amanda Collins68', 'amanda_collins68');
SELECT restore_rollcall_user('jacob.vega518@hotmail.com', 'HappyJV77@', 'Jacob Vega518', 'jacob_vega518');
SELECT restore_rollcall_user('wesley.turner855@outlook.com', 'BoldWT75@', 'Wesley Turner855', 'wesley_turner855');
SELECT restore_rollcall_user('diego.jones395@outlook.com', 'NeonDJ97$', 'Diego Jones395', 'diego_jones395');
SELECT restore_rollcall_user('robert.edwards689@gmail.com', 'PeakRE94!', 'Robert Edwards689', 'robert_edwards689');
SELECT restore_rollcall_user('damian.lewis206@hotmail.com', 'FreeDL45*', 'Damian Lewis206', 'damian_lewis206');
SELECT restore_rollcall_user('emma.collins510@yahoo.com', 'CoolEC16!', 'Emma Collins510', 'emma_collins510');
SELECT restore_rollcall_user('allison.foster503@hotmail.com', 'PeakAF79!', 'Allison Foster503', 'allison_foster503');
SELECT restore_rollcall_user('jake.perez320@icloud.com', 'CoolJP82$', 'Jake Perez320', 'jake_perez320');
SELECT restore_rollcall_user('diamond.turner329@gmail.com', 'EpicDT54*', 'Diamond Turner329', 'diamond_turner329');
SELECT restore_rollcall_user('taylor.king254@yahoo.com', 'CoolTK49!', 'Taylor King254', 'taylor_king254');
SELECT restore_rollcall_user('darryl.anderson585@icloud.com', 'FreeDA22@', 'Darryl Anderson585', 'darryl_anderson585');
SELECT restore_rollcall_user('christian.gomez49@outlook.com', 'BoldCG89!', 'Christian Gomez49', 'christian_gomez49');
SELECT restore_rollcall_user('ben.baptiste680@hotmail.com', 'WildBB42*', 'Ben Baptiste680', 'ben_baptiste680');
SELECT restore_rollcall_user('marcus.sullivan958@hotmail.com', 'FreeMS28@', 'Marcus Sullivan958', 'marcus_sullivan958');
SELECT restore_rollcall_user('taylor.hill263@hotmail.com', 'BoldTH24@', 'Taylor Hill263', 'taylor_hill263');
SELECT restore_rollcall_user('joshua.davis30@outlook.com', 'FastJD92!', 'Joshua Davis30', 'joshua_davis30');
SELECT restore_rollcall_user('ethan.rogers535@hotmail.com', 'BoldER86!', 'Ethan Rogers535', 'ethan_rogers535');
SELECT restore_rollcall_user('kayla.howard261@hotmail.com', 'CoolKH50*', 'Kayla Howard261', 'kayla_howard261');
SELECT restore_rollcall_user('chris.ward566@icloud.com', 'EpicCW97!', 'Chris Ward566', 'chris_ward566');
SELECT restore_rollcall_user('wesley.stewart809@gmail.com', 'FreeWS70$', 'Wesley Stewart809', 'wesley_stewart809');
SELECT restore_rollcall_user('chris.taylor811@yahoo.com', 'NeonCT50*', 'Chris Taylor811', 'chris_taylor811');
SELECT restore_rollcall_user('noah.nelson267@yahoo.com', 'BoldNN20$', 'Noah Nelson267', 'noah_nelson267');
SELECT restore_rollcall_user('dominic.ortiz719@yahoo.com', 'ChillDO43@', 'Dominic Ortiz719', 'dominic_ortiz719');
SELECT restore_rollcall_user('alejandro.morales230@yahoo.com', 'NeonAM73$', 'Alejandro Morales230', 'alejandro_morales230');
SELECT restore_rollcall_user('brooklyn.jackson633@icloud.com', 'ChillBJ97$', 'Brooklyn Jackson633', 'brooklyn_jackson633');
SELECT restore_rollcall_user('kayla.white754@hotmail.com', 'PeakKW17!', 'Kayla White754', 'kayla_white754');
SELECT restore_rollcall_user('genesis.robinson184@outlook.com', 'FreeGR53$', 'Genesis Robinson184', 'genesis_robinson184');
SELECT restore_rollcall_user('gavin.phillips949@icloud.com', 'ChillGP43*', 'Gavin Phillips949', 'gavin_phillips949');
SELECT restore_rollcall_user('cameron.parker723@icloud.com', 'FreeCP15$', 'Cameron Parker723', 'cameron_parker723');
SELECT restore_rollcall_user('maya.evans843@outlook.com', 'HappyME77*', 'Maya Evans843', 'maya_evans843');
SELECT restore_rollcall_user('gabrielle.martinez952@gmail.com', 'CoolGM68$', 'Gabrielle Martinez952', 'gabrielle_martinez952');
SELECT restore_rollcall_user('nora.baptiste561@hotmail.com', 'WildNB42@', 'Nora Baptiste561', 'nora_baptiste561');
SELECT restore_rollcall_user('sophia.hughes306@icloud.com', 'NeonSH97*', 'Sophia Hughes306', 'sophia_hughes306');
SELECT restore_rollcall_user('zoe.martin577@hotmail.com', 'WildZM57*', 'Zoe Martin577', 'zoe_martin577');
SELECT restore_rollcall_user('lara.taylor540@hotmail.com', 'CoolLT71#', 'Lara Taylor540', 'lara_taylor540');
SELECT restore_rollcall_user('cody.bryant111@hotmail.com', 'CoolCB69*', 'Cody Bryant111', 'cody_bryant111');
SELECT restore_rollcall_user('nicole.russell639@outlook.com', 'BoldNR33!', 'Nicole Russell639', 'nicole_russell639');
SELECT restore_rollcall_user('james.thomas709@icloud.com', 'ChillJT88#', 'James Thomas709', 'james_thomas709');
SELECT restore_rollcall_user('jessica.vega493@yahoo.com', 'PeakJV34!', 'Jessica Vega493', 'jessica_vega493');
SELECT restore_rollcall_user('ariana.parker600@yahoo.com', 'ChillAP60!', 'Ariana Parker600', 'ariana_parker600');
SELECT restore_rollcall_user('lena.white20@icloud.com', 'NeonLW92$', 'Lena White20', 'lena_white20');
SELECT restore_rollcall_user('darryl.walker135@outlook.com', 'EpicDW70@', 'Darryl Walker135', 'darryl_walker135');
SELECT restore_rollcall_user('morgan.griffin49@gmail.com', 'EpicMG96@', 'Morgan Griffin49', 'morgan_griffin49');
SELECT restore_rollcall_user('dion.green230@icloud.com', 'HappyDG81#', 'Dion Green230', 'dion_green230');
SELECT restore_rollcall_user('finn.garcia746@outlook.com', 'PeakFG73!', 'Finn Garcia746', 'finn_garcia746');
SELECT restore_rollcall_user('thomas.patel855@icloud.com', 'FastTP20#', 'Thomas Patel855', 'thomas_patel855');
SELECT restore_rollcall_user('alexandra.vega967@gmail.com', 'HappyAV76!', 'Alexandra Vega967', 'alexandra_vega967');
SELECT restore_rollcall_user('cameron.thompson60@hotmail.com', 'PeakCT48#', 'Cameron Thompson60', 'cameron_thompson60');
SELECT restore_rollcall_user('savannah.williams554@outlook.com', 'PeakSW80#', 'Savannah Williams554', 'savannah_williams554');
SELECT restore_rollcall_user('connor.reyes643@hotmail.com', 'CoolCR67#', 'Connor Reyes643', 'connor_reyes643');
SELECT restore_rollcall_user('samantha.reed336@hotmail.com', 'FreeSR22@', 'Samantha Reed336', 'samantha_reed336');
SELECT restore_rollcall_user('bryan.miller532@icloud.com', 'WildBM66$', 'Bryan Miller532', 'bryan_miller532');
SELECT restore_rollcall_user('kayla.nguyen765@yahoo.com', 'ChillKN62!', 'Kayla Nguyen765', 'kayla_nguyen765');
SELECT restore_rollcall_user('nathan.long498@gmail.com', 'ChillNL63!', 'Nathan Long498', 'nathan_long498');
SELECT restore_rollcall_user('crystal.nelson487@hotmail.com', 'PeakCN91$', 'Crystal Nelson487', 'crystal_nelson487');
SELECT restore_rollcall_user('savannah.green554@gmail.com', 'NeonSG92!', 'Savannah Green554', 'savannah_green554');
SELECT restore_rollcall_user('finn.thompson986@gmail.com', 'BoldFT84$', 'Finn Thompson986', 'finn_thompson986');
SELECT restore_rollcall_user('paige.morris25@hotmail.com', 'CoolPM24!', 'Paige Morris25', 'paige_morris25');
SELECT restore_rollcall_user('connor.scott28@gmail.com', 'EpicCS28$', 'Connor Scott28', 'connor_scott28');
SELECT restore_rollcall_user('noah.ortiz68@icloud.com', 'HappyNO44*', 'Noah Ortiz68', 'noah_ortiz68');
SELECT restore_rollcall_user('lily.richardson463@gmail.com', 'ChillLR47@', 'Lily Richardson463', 'lily_richardson463');
SELECT restore_rollcall_user('kayla.ross47@yahoo.com', 'CoolKR27*', 'Kayla Ross47', 'kayla_ross47');
SELECT restore_rollcall_user('aiden.sanders924@gmail.com', 'PeakAS99$', 'Aiden Sanders924', 'aiden_sanders924');
SELECT restore_rollcall_user('savannah.edwards474@outlook.com', 'HappySE38!', 'Savannah Edwards474', 'savannah_edwards474');
SELECT restore_rollcall_user('ricky.barnes927@hotmail.com', 'BoldRB91$', 'Ricky Barnes927', 'ricky_barnes927');
SELECT restore_rollcall_user('damian.russell131@outlook.com', 'NeonDR34!', 'Damian Russell131', 'damian_russell131');
SELECT restore_rollcall_user('austin.lewis906@yahoo.com', 'PeakAL67#', 'Austin Lewis906', 'austin_lewis906');
SELECT restore_rollcall_user('derek.hall338@outlook.com', 'HappyDH71$', 'Derek Hall338', 'derek_hall338');
SELECT restore_rollcall_user('elena.stewart128@gmail.com', 'EpicES98!', 'Elena Stewart128', 'elena_stewart128');
SELECT restore_rollcall_user('santiago.miller239@hotmail.com', 'WildSM89*', 'Santiago Miller239', 'santiago_miller239');
SELECT restore_rollcall_user('emma.clark608@yahoo.com', 'PeakEC42#', 'Emma Clark608', 'emma_clark608');
SELECT restore_rollcall_user('nicholas.ross983@outlook.com', 'FastNR28$', 'Nicholas Ross983', 'nicholas_ross983');
SELECT restore_rollcall_user('tyler.king656@yahoo.com', 'FreeTK98$', 'Tyler King656', 'tyler_king656');
SELECT restore_rollcall_user('kylie.adams478@hotmail.com', 'FreeKA52$', 'Kylie Adams478', 'kylie_adams478');
SELECT restore_rollcall_user('cole.coleman451@yahoo.com', 'BoldCC35#', 'Cole Coleman451', 'cole_coleman451');
SELECT restore_rollcall_user('jose.anderson933@gmail.com', 'WildJA93!', 'Jose Anderson933', 'jose_anderson933');
SELECT restore_rollcall_user('hector.cook546@icloud.com', 'WildHC91@', 'Hector Cook546', 'hector_cook546');
SELECT restore_rollcall_user('amanda.mensah521@icloud.com', 'FreeAM32#', 'Amanda Mensah521', 'amanda_mensah521');
SELECT restore_rollcall_user('justin.gonzalez884@yahoo.com', 'NeonJG64$', 'Justin Gonzalez884', 'justin_gonzalez884');
SELECT restore_rollcall_user('lauren.ross525@hotmail.com', 'FreeLR65$', 'Lauren Ross525', 'lauren_ross525');
SELECT restore_rollcall_user('rebecca.butler526@hotmail.com', 'BoldRB22!', 'Rebecca Butler526', 'rebecca_butler526');
SELECT restore_rollcall_user('jessica.watson935@outlook.com', 'EpicJW61$', 'Jessica Watson935', 'jessica_watson935');
SELECT restore_rollcall_user('alexis.kim867@yahoo.com', 'WildAK36$', 'Alexis Kim867', 'alexis_kim867');
SELECT restore_rollcall_user('owen.gonzalez703@icloud.com', 'HappyOG82!', 'Owen Gonzalez703', 'owen_gonzalez703');
SELECT restore_rollcall_user('morgan.campbell692@hotmail.com', 'ChillMC72!', 'Morgan Campbell692', 'morgan_campbell692');
SELECT restore_rollcall_user('alejandro.brooks12@yahoo.com', 'WildAB30!', 'Alejandro Brooks12', 'alejandro_brooks12');
SELECT restore_rollcall_user('julia.jenkins163@hotmail.com', 'PeakJJ97$', 'Julia Jenkins163', 'julia_jenkins163');
SELECT restore_rollcall_user('bryan.kelly472@icloud.com', 'FreeBK54#', 'Bryan Kelly472', 'bryan_kelly472');
SELECT restore_rollcall_user('sebastian.washington907@yahoo.com', 'PeakSW47!', 'Sebastian Washington907', 'sebastian_washington907');
SELECT restore_rollcall_user('tanner.nelson213@hotmail.com', 'FreeTN58#', 'Tanner Nelson213', 'tanner_nelson213');
SELECT restore_rollcall_user('ariana.ortiz562@yahoo.com', 'FreeAO45@', 'Ariana Ortiz562', 'ariana_ortiz562');
SELECT restore_rollcall_user('james.bryant158@icloud.com', 'HappyJB96*', 'James Bryant158', 'james_bryant158');
SELECT restore_rollcall_user('savannah.ward54@hotmail.com', 'BoldSW41#', 'Savannah Ward54', 'savannah_ward54');
SELECT restore_rollcall_user('charlotte.moore836@outlook.com', 'BoldCM89@', 'Charlotte Moore836', 'charlotte_moore836');
SELECT restore_rollcall_user('savannah.gomez68@outlook.com', 'BoldSG62#', 'Savannah Gomez68', 'savannah_gomez68');
SELECT restore_rollcall_user('grace.kelly872@icloud.com', 'ChillGK67$', 'Grace Kelly872', 'grace_kelly872');
SELECT restore_rollcall_user('lily.smith141@outlook.com', 'BoldLS29$', 'Lily Smith141', 'lily_smith141');
SELECT restore_rollcall_user('matthew.johnson811@icloud.com', 'BoldMJ52#', 'Matthew Johnson811', 'matthew_johnson811');
SELECT restore_rollcall_user('destiny.lopez188@icloud.com', 'CoolDL34!', 'Destiny Lopez188', 'destiny_lopez188');
SELECT restore_rollcall_user('valentina.williams169@yahoo.com', 'FastVW87@', 'Valentina Williams169', 'valentina_williams169');
SELECT restore_rollcall_user('amanda.murphy625@icloud.com', 'HappyAM58$', 'Amanda Murphy625', 'amanda_murphy625');
SELECT restore_rollcall_user('amanda.foster5@gmail.com', 'WildAF60#', 'Amanda Foster5', 'amanda_foster5');
SELECT restore_rollcall_user('pedro.ramirez714@gmail.com', 'WildPR41@', 'Pedro Ramirez714', 'pedro_ramirez714');
SELECT restore_rollcall_user('bailey.coleman408@hotmail.com', 'WildBC31$', 'Bailey Coleman408', 'bailey_coleman408');
SELECT restore_rollcall_user('emma.sullivan834@yahoo.com', 'WildES99#', 'Emma Sullivan834', 'emma_sullivan834');
SELECT restore_rollcall_user('melissa.wilson181@outlook.com', 'BoldMW72@', 'Melissa Wilson181', 'melissa_wilson181');
SELECT restore_rollcall_user('wesley.stewart82@outlook.com', 'CoolWS53!', 'Wesley Stewart82', 'wesley_stewart82');
SELECT restore_rollcall_user('elena.gomez385@hotmail.com', 'FreeEG53*', 'Elena Gomez385', 'elena_gomez385');
SELECT restore_rollcall_user('rebecca.kelly468@icloud.com', 'ChillRK25*', 'Rebecca Kelly468', 'rebecca_kelly468');
SELECT restore_rollcall_user('brenda.mitchell654@outlook.com', 'HappyBM51$', 'Brenda Mitchell654', 'brenda_mitchell654');
SELECT restore_rollcall_user('angel.thompson301@hotmail.com', 'PeakAT83*', 'Angel Thompson301', 'angel_thompson301');
SELECT restore_rollcall_user('james.nelson679@hotmail.com', 'BoldJN31!', 'James Nelson679', 'james_nelson679');
SELECT restore_rollcall_user('kylie.williams975@gmail.com', 'FreeKW21#', 'Kylie Williams975', 'kylie_williams975');
SELECT restore_rollcall_user('ethan.campbell960@yahoo.com', 'EpicEC58*', 'Ethan Campbell960', 'ethan_campbell960');
SELECT restore_rollcall_user('emma.martinez873@icloud.com', 'BoldEM73$', 'Emma Martinez873', 'emma_martinez873');
SELECT restore_rollcall_user('denise.johnson706@gmail.com', 'ChillDJ71@', 'Denise Johnson706', 'denise_johnson706');
SELECT restore_rollcall_user('chris.kim745@icloud.com', 'FastCK12*', 'Chris Kim745', 'chris_kim745');
SELECT restore_rollcall_user('jordan.washington100@yahoo.com', 'HappyJW48$', 'Jordan Washington100', 'jordan_washington100');
SELECT restore_rollcall_user('ricky.williams695@yahoo.com', 'FastRW17!', 'Ricky Williams695', 'ricky_williams695');
SELECT restore_rollcall_user('lily.barnes407@icloud.com', 'FastLB93$', 'Lily Barnes407', 'lily_barnes407');
SELECT restore_rollcall_user('gabrielle.perez24@hotmail.com', 'CoolGP85@', 'Gabrielle Perez24', 'gabrielle_perez24');
SELECT restore_rollcall_user('sophia.vasquez570@hotmail.com', 'PeakSV84*', 'Sophia Vasquez570', 'sophia_vasquez570');
SELECT restore_rollcall_user('nicole.collins589@yahoo.com', 'PeakNC42!', 'Nicole Collins589', 'nicole_collins589');
SELECT restore_rollcall_user('logan.james927@outlook.com', 'ChillLJ72#', 'Logan James927', 'logan_james927');
SELECT restore_rollcall_user('kevin.cooper606@outlook.com', 'ChillKC64!', 'Kevin Cooper606', 'kevin_cooper606');
SELECT restore_rollcall_user('christian.garcia649@yahoo.com', 'PeakCG87@', 'Christian Garcia649', 'christian_garcia649');
SELECT restore_rollcall_user('claudia.mitchell656@gmail.com', 'NeonCM28@', 'Claudia Mitchell656', 'claudia_mitchell656');
SELECT restore_rollcall_user('darryl.morales542@outlook.com', 'ChillDM22!', 'Darryl Morales542', 'darryl_morales542');
SELECT restore_rollcall_user('anthony.russell10@hotmail.com', 'FastAR28$', 'Anthony Russell10', 'anthony_russell10');
SELECT restore_rollcall_user('wesley.lee294@outlook.com', 'BoldWL49!', 'Wesley Lee294', 'wesley_lee294');
SELECT restore_rollcall_user('anthony.phillips715@gmail.com', 'ChillAP34!', 'Anthony Phillips715', 'anthony_phillips715');
SELECT restore_rollcall_user('jasmine.bryant527@outlook.com', 'FastJB57!', 'Jasmine Bryant527', 'jasmine_bryant527');
SELECT restore_rollcall_user('kevin.jenkins958@icloud.com', 'EpicKJ10*', 'Kevin Jenkins958', 'kevin_jenkins958');
SELECT restore_rollcall_user('elijah.morris87@hotmail.com', 'CoolEM72!', 'Elijah Morris87', 'elijah_morris87');
SELECT restore_rollcall_user('riley.morgan832@outlook.com', 'FreeRM30@', 'Riley Morgan832', 'riley_morgan832');
SELECT restore_rollcall_user('tiffany.wright165@yahoo.com', 'NeonTW25$', 'Tiffany Wright165', 'tiffany_wright165');
SELECT restore_rollcall_user('gavin.cruz14@yahoo.com', 'WildGC86!', 'Gavin Cruz14', 'gavin_cruz14');
SELECT restore_rollcall_user('logan.howard718@yahoo.com', 'FreeLH23*', 'Logan Howard718', 'logan_howard718');
SELECT restore_rollcall_user('valentina.anderson886@gmail.com', 'PeakVA49@', 'Valentina Anderson886', 'valentina_anderson886');
SELECT restore_rollcall_user('morgan.coleman288@outlook.com', 'EpicMC16@', 'Morgan Coleman288', 'morgan_coleman288');
SELECT restore_rollcall_user('victor.evans373@outlook.com', 'HappyVE97*', 'Victor Evans373', 'victor_evans373');
SELECT restore_rollcall_user('dominic.clark43@hotmail.com', 'FreeDC22!', 'Dominic Clark43', 'dominic_clark43');
SELECT restore_rollcall_user('courtney.king645@gmail.com', 'FreeCK63*', 'Courtney King645', 'courtney_king645');
SELECT restore_rollcall_user('cassidy.ramirez449@hotmail.com', 'WildCR61*', 'Cassidy Ramirez449', 'cassidy_ramirez449');
SELECT restore_rollcall_user('brenda.nguyen266@outlook.com', 'NeonBN80!', 'Brenda Nguyen266', 'brenda_nguyen266');
SELECT restore_rollcall_user('chris.taylor548@gmail.com', 'ChillCT57#', 'Chris Taylor548', 'chris_taylor548');
SELECT restore_rollcall_user('olivia.brooks225@outlook.com', 'HappyOB78*', 'Olivia Brooks225', 'olivia_brooks225');
SELECT restore_rollcall_user('zach.gonzalez209@hotmail.com', 'FreeZG39$', 'Zach Gonzalez209', 'zach_gonzalez209');
SELECT restore_rollcall_user('maya.anderson907@yahoo.com', 'ChillMA34!', 'Maya Anderson907', 'maya_anderson907');
SELECT restore_rollcall_user('bryan.cooper387@icloud.com', 'HappyBC26@', 'Bryan Cooper387', 'bryan_cooper387');
SELECT restore_rollcall_user('hannah.patterson836@yahoo.com', 'FastHP41!', 'Hannah Patterson836', 'hannah_patterson836');
SELECT restore_rollcall_user('hector.adams233@icloud.com', 'EpicHA93#', 'Hector Adams233', 'hector_adams233');
SELECT restore_rollcall_user('ethan.gonzalez366@gmail.com', 'CoolEG15*', 'Ethan Gonzalez366', 'ethan_gonzalez366');
SELECT restore_rollcall_user('morgan.smith897@gmail.com', 'EpicMS43!', 'Morgan Smith897', 'morgan_smith897');
SELECT restore_rollcall_user('matthew.cox131@yahoo.com', 'EpicMC73$', 'Matthew Cox131', 'matthew_cox131');
SELECT restore_rollcall_user('cassidy.richardson86@hotmail.com', 'ChillCR98@', 'Cassidy Richardson86', 'cassidy_richardson86');
SELECT restore_rollcall_user('pedro.lewis472@yahoo.com', 'BoldPL38!', 'Pedro Lewis472', 'pedro_lewis472');
SELECT restore_rollcall_user('anthony.reyes151@outlook.com', 'BoldAR19!', 'Anthony Reyes151', 'anthony_reyes151');
SELECT restore_rollcall_user('zach.okafor114@yahoo.com', 'ChillZO32*', 'Zach Okafor114', 'zach_okafor114');
SELECT restore_rollcall_user('dakota.price434@yahoo.com', 'WildDP26@', 'Dakota Price434', 'dakota_price434');
SELECT restore_rollcall_user('santiago.diaz663@icloud.com', 'CoolSD23!', 'Santiago Diaz663', 'santiago_diaz663');

-- SEEDING TRIBAL GROUPS
INSERT INTO public.groups (name, category, city, description, coords, image) VALUES ('Warzone 2.0 PBC', 'Gaming', 'Palm Beach Gardens', 'Official PBC Gaming group.', jsonb_build_array(26.6908, -80.1504), 'https://images.unsplash.com/photo-1542751371-adc38448a05e?q=80&w=800') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.groups (name, category, city, description, coords, image) VALUES ('Valorant WPB Hub', 'Gaming', 'Delray Beach', 'Official PBC Gaming group.', jsonb_build_array(26.8885, -80.1157), 'https://images.unsplash.com/photo-1542751371-adc38448a05e?q=80&w=800') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.groups (name, category, city, description, coords, image) VALUES ('Apex Legends Squads', 'Gaming', 'Lake Worth', 'Official PBC Gaming group.', jsonb_build_array(26.6054, -80.1823), 'https://images.unsplash.com/photo-1542751371-adc38448a05e?q=80&w=800') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.groups (name, category, city, description, coords, image) VALUES ('LoL Florida West', 'Gaming', 'Delray Beach', 'Official PBC Gaming group.', jsonb_build_array(26.8728, -80.0204), 'https://images.unsplash.com/photo-1542751371-adc38448a05e?q=80&w=800') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.groups (name, category, city, description, coords, image) VALUES ('Fortnite Zero Build', 'Gaming', 'Palm Beach Gardens', 'Official PBC Gaming group.', jsonb_build_array(26.5702, -80.1828), 'https://images.unsplash.com/photo-1542751371-adc38448a05e?q=80&w=800') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.groups (name, category, city, description, coords, image) VALUES ('Minecraft Survival', 'Gaming', 'Boca Raton', 'Official PBC Gaming group.', jsonb_build_array(26.7583, -80.0588), 'https://images.unsplash.com/photo-1542751371-adc38448a05e?q=80&w=800') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.groups (name, category, city, description, coords, image) VALUES ('Roblox Dev Group', 'Gaming', 'West Palm Beach', 'Official PBC Gaming group.', jsonb_build_array(26.583, -80.1065), 'https://images.unsplash.com/photo-1542751371-adc38448a05e?q=80&w=800') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.groups (name, category, city, description, coords, image) VALUES ('CS:GO Veterans', 'Gaming', 'Jupiter', 'Official PBC Gaming group.', jsonb_build_array(26.526, -80.1826), 'https://images.unsplash.com/photo-1542751371-adc38448a05e?q=80&w=800') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.groups (name, category, city, description, coords, image) VALUES ('Overwatch 2 Mains', 'Gaming', 'Palm Beach Gardens', 'Official PBC Gaming group.', jsonb_build_array(26.4977, -80.0865), 'https://images.unsplash.com/photo-1542751371-adc38448a05e?q=80&w=800') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.groups (name, category, city, description, coords, image) VALUES ('FIFA 24 Pro Clubs', 'Gaming', 'Wellington', 'Official PBC Gaming group.', jsonb_build_array(26.6963, -80.197), 'https://images.unsplash.com/photo-1542751371-adc38448a05e?q=80&w=800') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.groups (name, category, city, description, coords, image) VALUES ('Madden 24 PBC League', 'Gaming', 'Delray Beach', 'Official PBC Gaming group.', jsonb_build_array(26.4883, -80.0158), 'https://images.unsplash.com/photo-1542751371-adc38448a05e?q=80&w=800') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.groups (name, category, city, description, coords, image) VALUES ('NBA 2K24 Parks', 'Gaming', 'Wellington', 'Official PBC Gaming group.', jsonb_build_array(26.5649, -80.1798), 'https://images.unsplash.com/photo-1542751371-adc38448a05e?q=80&w=800') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.groups (name, category, city, description, coords, image) VALUES ('Street Fighter 6', 'Gaming', 'Delray Beach', 'Official PBC Gaming group.', jsonb_build_array(26.852, -80.1622), 'https://images.unsplash.com/photo-1542751371-adc38448a05e?q=80&w=800') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.groups (name, category, city, description, coords, image) VALUES ('Tekken 8 Dojo', 'Gaming', 'Delray Beach', 'Official PBC Gaming group.', jsonb_build_array(26.6039, -80.1024), 'https://images.unsplash.com/photo-1542751371-adc38448a05e?q=80&w=800') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.groups (name, category, city, description, coords, image) VALUES ('MK1 Tournament Hub', 'Gaming', 'Jupiter', 'Official PBC Gaming group.', jsonb_build_array(26.6681, -80.1361), 'https://images.unsplash.com/photo-1542751371-adc38448a05e?q=80&w=800') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.groups (name, category, city, description, coords, image) VALUES ('Elden Ring Co-op', 'Gaming', 'Lake Worth', 'Official PBC Gaming group.', jsonb_build_array(26.8211, -80.0858), 'https://images.unsplash.com/photo-1542751371-adc38448a05e?q=80&w=800') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.groups (name, category, city, description, coords, image) VALUES ('Baldur's Gate 3 Party', 'Gaming', 'West Palm Beach', 'Official PBC Gaming group.', jsonb_build_array(26.6994, -80.0642), 'https://images.unsplash.com/photo-1542751371-adc38448a05e?q=80&w=800') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.groups (name, category, city, description, coords, image) VALUES ('Helldivers 2 PBC', 'Gaming', 'Lake Worth', 'Official PBC Gaming group.', jsonb_build_array(26.4791, -80.1968), 'https://images.unsplash.com/photo-1542751371-adc38448a05e?q=80&w=800') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.groups (name, category, city, description, coords, image) VALUES ('Palworld Builders', 'Gaming', 'Wellington', 'Official PBC Gaming group.', jsonb_build_array(26.8036, -80.1258), 'https://images.unsplash.com/photo-1542751371-adc38448a05e?q=80&w=800') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.groups (name, category, city, description, coords, image) VALUES ('Destiny 2 Raids', 'Gaming', 'Jupiter', 'Official PBC Gaming group.', jsonb_build_array(26.849, -80.1683), 'https://images.unsplash.com/photo-1542751371-adc38448a05e?q=80&w=800') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.groups (name, category, city, description, coords, image) VALUES ('D&D 5e PBC', 'Tabletop', 'Delray Beach', 'Official PBC Tabletop group.', jsonb_build_array(26.4617, -80.1644), 'https://images.unsplash.com/photo-1611996591638-8055c06d152f?q=80&w=800') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.groups (name, category, city, description, coords, image) VALUES ('Pathfinder 2e Society', 'Tabletop', 'West Palm Beach', 'Official PBC Tabletop group.', jsonb_build_array(26.7646, -80.084), 'https://images.unsplash.com/photo-1611996591638-8055c06d152f?q=80&w=800') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.groups (name, category, city, description, coords, image) VALUES ('Warhammer 40k WPB', 'Tabletop', 'Delray Beach', 'Official PBC Tabletop group.', jsonb_build_array(26.4624, -80.099), 'https://images.unsplash.com/photo-1611996591638-8055c06d152f?q=80&w=800') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.groups (name, category, city, description, coords, image) VALUES ('Catan Nights', 'Tabletop', 'Delray Beach', 'Official PBC Tabletop group.', jsonb_build_array(26.6603, -80.1196), 'https://images.unsplash.com/photo-1611996591638-8055c06d152f?q=80&w=800') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.groups (name, category, city, description, coords, image) VALUES ('Ticket to Ride', 'Tabletop', 'Wellington', 'Official PBC Tabletop group.', jsonb_build_array(26.3461, -80.1228), 'https://images.unsplash.com/photo-1611996591638-8055c06d152f?q=80&w=800') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.groups (name, category, city, description, coords, image) VALUES ('Pandemic Squad', 'Tabletop', 'Lake Worth', 'Official PBC Tabletop group.', jsonb_build_array(26.4401, -80.0868), 'https://images.unsplash.com/photo-1611996591638-8055c06d152f?q=80&w=800') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.groups (name, category, city, description, coords, image) VALUES ('Terraforming Mars', 'Tabletop', 'Palm Beach Gardens', 'Official PBC Tabletop group.', jsonb_build_array(26.8027, -80.1815), 'https://images.unsplash.com/photo-1611996591638-8055c06d152f?q=80&w=800') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.groups (name, category, city, description, coords, image) VALUES ('Gloomhaven Party', 'Tabletop', 'West Palm Beach', 'Official PBC Tabletop group.', jsonb_build_array(26.4805, -80.1224), 'https://images.unsplash.com/photo-1611996591638-8055c06d152f?q=80&w=800') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.groups (name, category, city, description, coords, image) VALUES ('Scythe PBC', 'Tabletop', 'Wellington', 'Official PBC Tabletop group.', jsonb_build_array(26.7933, -80.1308), 'https://images.unsplash.com/photo-1611996591638-8055c06d152f?q=80&w=800') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.groups (name, category, city, description, coords, image) VALUES ('7 Wonders Club', 'Tabletop', 'Boca Raton', 'Official PBC Tabletop group.', jsonb_build_array(26.4237, -80.1256), 'https://images.unsplash.com/photo-1611996591638-8055c06d152f?q=80&w=800') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.groups (name, category, city, description, coords, image) VALUES ('Pickleball Lake Worth', 'Sports', 'Delray Beach', 'Official PBC Sports group.', jsonb_build_array(26.3672, -80.0656), 'https://images.unsplash.com/photo-1574629810360-7efbbe195018?q=80&w=800') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.groups (name, category, city, description, coords, image) VALUES ('Soccer WPB League', 'Sports', 'Delray Beach', 'Official PBC Sports group.', jsonb_build_array(26.5428, -80.0839), 'https://images.unsplash.com/photo-1574629810360-7efbbe195018?q=80&w=800') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.groups (name, category, city, description, coords, image) VALUES ('Tennis PBC Open', 'Sports', 'Palm Beach Gardens', 'Official PBC Sports group.', jsonb_build_array(26.8789, -80.1128), 'https://images.unsplash.com/photo-1574629810360-7efbbe195018?q=80&w=800') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.groups (name, category, city, description, coords, image) VALUES ('Basketball Courts', 'Sports', 'Wellington', 'Official PBC Sports group.', jsonb_build_array(26.5332, -80.0572), 'https://images.unsplash.com/photo-1574629810360-7efbbe195018?q=80&w=800') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.groups (name, category, city, description, coords, image) VALUES ('Golf PBC Society', 'Sports', 'Delray Beach', 'Official PBC Sports group.', jsonb_build_array(26.8385, -80.1231), 'https://images.unsplash.com/photo-1574629810360-7efbbe195018?q=80&w=800') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.groups (name, category, city, description, coords, image) VALUES ('Volleyball Beach Hub', 'Sports', 'Boca Raton', 'Official PBC Sports group.', jsonb_build_array(26.5876, -80.1839), 'https://images.unsplash.com/photo-1574629810360-7efbbe195018?q=80&w=800') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.groups (name, category, city, description, coords, image) VALUES ('Running PBC', 'Sports', 'Delray Beach', 'Official PBC Sports group.', jsonb_build_array(26.432, -80.0179), 'https://images.unsplash.com/photo-1574629810360-7efbbe195018?q=80&w=800') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.groups (name, category, city, description, coords, image) VALUES ('Cycling WPB', 'Sports', 'West Palm Beach', 'Official PBC Sports group.', jsonb_build_array(26.6568, -80.1352), 'https://images.unsplash.com/photo-1574629810360-7efbbe195018?q=80&w=800') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.groups (name, category, city, description, coords, image) VALUES ('Swimming PBC', 'Sports', 'West Palm Beach', 'Official PBC Sports group.', jsonb_build_array(26.3049, -80.1999), 'https://images.unsplash.com/photo-1574629810360-7efbbe195018?q=80&w=800') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.groups (name, category, city, description, coords, image) VALUES ('Padel Club', 'Sports', 'Lake Worth', 'Official PBC Sports group.', jsonb_build_array(26.4244, -80.0825), 'https://images.unsplash.com/photo-1574629810360-7efbbe195018?q=80&w=800') ON CONFLICT (name) DO NOTHING;

-- AUTO-JOINING RESIDENTS TO GROUPS

DO $$
DECLARE
    u RECORD;
    g RECORD;
BEGIN
    FOR u IN SELECT id FROM public.profiles WHERE is_verified_organizer = false LOOP
        FOR g IN (SELECT id FROM public.groups ORDER BY random() LIMIT (random()*2 + 1)::int) LOOP
            INSERT INTO public.memberships (user_id, group_id) VALUES (u.id, g.id) ON CONFLICT DO NOTHING;
        END LOOP;
    END LOOP;
END $$;
